---
title: ""
author:
  - William Kumler
  - Laura T. Carlson
  - Anitra E. Ingalls
output: 
  word_document:
    reference_docx: Frontiers_Template.docx
bibliography:
- Exported Items.bib
- r-packages.bib
csl: frontiers-in-marine-science.csl
---

```{r Run analysis, include=FALSE}
# TBD
```

```{r setup}
knitr::opts_chunk$set(echo = FALSE, message=FALSE, warning=FALSE)
library(tidyverse)
library(ggh4x)
library(patchwork)
library(ggtext)
library(minpack.lm)

parametadata <- read_csv("metadata/parametadata.csv") %>%
  # filter(IS_type=="noIS") %>%
  filter(polarity=="pos") %>%
  filter(samp_type=="Smp") %>%
  mutate(startime=factor(startime, levels=c("Morn", "Eve"))) %>%
  mutate(depth=factor(depth, levels=c("Surf", "Deep"))) %>%
  mutate(amendment=factor(amendment, levels=c("Amm", "Nit", "Arg", "GMP"))) %>%
  arrange(amendment, depth, timepoint_num, startime) %>%
  mutate(timepoint=fct_inorder(timepoint))
peak_areas <- read_csv("targeted/all_peak_areas_w_isos.csv") %>%
  left_join(parametadata %>% distinct(filename, shortname))
all_stans <- read_csv("metadata/all_stans.csv")
maa_names <- c("Also Palythene/Usujirene?", "Shinorine?", "Mycosporine-glycine?", 
               "Palythine?", "Another Palythene/Usujirene?", "Porphyra-334?", 
               "Also Porphyra-334?", "Asterina-330?", "Palythene/Usujirene?",
               "Mycosporine-2-glycine?")
nucleo_names <- c("5-Methylcytosine", "Adenosine", "Cytidine", "Adenine", "Guanosine",
                  "Cytosine", "Hypoxanthine/Allopurinol", "Guanine", "Deoxycytidine?",
                  "Deoxyadenosine", "Deoxyguanosine?")
betaine_names <- c("beta-Alaninebetaine", "Glycine betaine", "Homarine", "Trigonelline",
                   "Choline", "Glycerophosphocholine", "Homoserine betaine?", 
                   "Threonine betaine?", "Proline betaine",
                   "(3-Carboxypropyl)trimethylammonium", "O-Acetylcarnitine", 
                   "Betonicine", "Acetylcholine", "Phosphocholine")
non_n_names <- c("Dimethylsulfonioacetate", "Dimethylsulfoniopropionate",
                 "Arsenobetaine", "Dimethylsulfoxonium propionate?", "Gonyol",
                 "2-O-alpha-D-Glucosylglycerol")
aa_names <- c("Glutamine", "Aspartic acid", "Glutamic acid/beta-Glutamic acid",
              "Asparagine", "Alanine", "Methionine", "Arginine", "Proline",
              "Lysine", "Threonine/Homoserine", "Serine", "Glycine", "Histidine",
              "Leucine/Isoleucine", "Valine", "Arginine")
bad_cmpds <- c("Melamine", "Uridine", "Itaconic acid?", "Inosine", "Dexpanthenol", 
               "Choline sulfate", "5-Hydroxyectoine", "L-Tyrosine")
samp_areas <- parametadata %>%
  filter(samp_type=="Smp") %>%
  distinct(shortname, depth) %>%
  left_join(peak_areas) %>%
  mutate(shortname=fct_inorder(shortname)) %>%
  filter(!compound_name%in%bad_cmpds) %>%
  filter(!(depth=="Deep" & compound_name%in%maa_names)) %>%
  select(-depth)
labeled_fracs <- samp_areas %>%
  mutate(labeled_frac=1-area/sum(area), .by = c("shortname", "compound_name")) %>%
  select(compound_name, iso_name, shortname, labeled_frac) %>%
  filter(str_detect(iso_name, "13C0, 15N0")) %>%
  select(-iso_name)
n_labeled_fracs <- samp_areas %>%
  filter(str_detect(iso_name, "13C0")) %>%
  filter(!str_detect(iso_name, "15N0") | str_detect(iso_name, "13C0, 15N0")) %>%
  mutate(labeled_frac=1-area/sum(area), .by = c("shortname", "compound_name")) %>%
  select(compound_name, iso_name, shortname, labeled_frac) %>%
  filter(str_detect(iso_name, "13C0, 15N0")) %>%
  select(-iso_name)
log_coef_df <- labeled_fracs %>%
  left_join(parametadata %>% distinct(shortname, amendment, depth, timepoint_num)) %>%
  nest(data=c(shortname, timepoint_num, labeled_frac)) %>%
  mutate(log_fit=map(data, ~glm(.x$labeled_frac~.x$timepoint_num, family="quasibinomial")),
         coefs=map(log_fit, function(x)broom::tidy(x))) %>%
  unnest(coefs) %>%
  select(compound_name, amendment, depth, term, estimate) %>%
  pivot_wider(names_from = term, values_from = estimate) %>%
  rename(intercept=`(Intercept)`, slope=`.x$timepoint_num`) %>%
  mutate(half_max=-intercept/slope, scale=1/slope) %>%
  mutate(frac_at_T24 = 1/(1+exp(-(intercept+slope*24))))
```


## Abstract

## Introduction

## Results

```{r figure 1 small heatmap compound groups}
class_levels <- c("Glutamine", "Glutamic acid", "Aspartic acid", "Asparagine", "Other amino acids", "Theanine?", "Citrulline", "Ectoine", "Guanine", "Other nucleic acids", "MAAs", "Betaines", "All others")

labeled_fracs %>%
  left_join(parametadata %>% distinct(shortname, timepoint, timepoint_num, depth, startime, amendment)) %>%
  filter(amendment=="Amm") %>%
  mutate(compound_name=str_remove_all(compound_name, "^L-")) %>%
  mutate(compound_name=str_remove(compound_name, "/beta-Glutamic acid")) %>%
  mutate(compound_class=case_when(
    compound_name%in%class_levels ~ compound_name,
    compound_name%in%maa_names~"MAAs",
    compound_name%in%aa_names~"Other amino acids",
    compound_name%in%nucleo_names~"Other nucleic acids",
    compound_name%in%betaine_names~"Betaines",
    TRUE~"All others"
  )) %>%
  mutate(compound_class=factor(compound_class, levels=class_levels)) %>%
  summarise(avg_frac=mean(labeled_frac), .by = c(compound_class, timepoint_num, startime, depth)) %>%
  mutate(color_group=paste(depth, startime)) %>%
  ggplot(aes(x=timepoint_num, y=avg_frac, color=color_group, fill=color_group)) +
  geom_smooth(method = "glm", formula = y~x, method.args = list(family = "quasibinomial"),
              fill="grey80") +
  geom_point(pch=21, color="black") +
  facet_wrap(~compound_class, ncol=5) +
  scale_y_continuous(labels = scales::label_percent(), breaks = c(0, 0.5, 1)) +
  scale_x_continuous(breaks = c(0.3, 1, 3, 10, 26), labels = c(0.3, 1, 3, 10, 26)) +
  scale_color_manual(breaks = c("Surf Morn", "Surf Eve", "Deep Morn", "Deep Eve"),
                     values = c("#FFD53D", "#DBA20A", "#256A76", "#003743")) +
  scale_fill_manual(breaks = c("Surf Morn", "Surf Eve", "Deep Morn", "Deep Eve"),
                     values = c("#FFD53D", "#DBA20A", "#256A76", "#003743")) +
  labs(x="Hours after 15N added", y="Fraction of metabolite labeled", color=NULL) +
  theme_bw() +
  guides(color = guide_legend(nrow = 2, override.aes = list(linewidth=2)),
         fill = "none") +
  theme(legend.position = "inside",
        legend.position.inside = c(0.8, 1/6),
        legend.location = "plot")

labeled_fracs %>%
  left_join(parametadata %>% distinct(shortname, timepoint, timepoint_num, depth, startime, amendment, tripl)) %>%
  filter(amendment=="Amm") %>%
  mutate(depth=factor(depth, levels=c("Surf", "Deep"), labels=c("Surface seawater (25 meters)", "Seawater from below DCM (175m)"))) %>%
  mutate(startime=factor(startime, levels=c("Morn", "Eve"), labels=c("6AM start", "6PM start"))) %>%
  mutate(compound_name=str_remove_all(compound_name, "^L-")) %>%
  mutate(compound_name=str_remove(compound_name, "/beta-Glutamic acid")) %>%
  mutate(compound_class=case_when(
    compound_name%in%c("Glutamine", "Aspartic acid", "Asparagine", "Glutamic acid", "Ectoine", "Theanine?", "Citrulline", "Guanine") ~ compound_name,
    compound_name%in%maa_names~"MAAs",
    compound_name%in%aa_names~"Other amino acids",
    compound_name%in%nucleo_names~"Other nucleic acids",
    compound_name%in%betaine_names~"Betaines",
    TRUE~"All others"
  )) %>%
  mutate(compound_class=factor(compound_class, levels=class_levels)) %>%
  summarise(avg_frac=mean(labeled_frac), .by = c(compound_class, timepoint, startime, depth, tripl)) %>%
  ggplot() +
  geom_raster(aes(x=timepoint, y=tripl, fill=avg_frac)) +
  geom_vline(xintercept = c(1.5:4.5), color="grey80") +
  facet_nested(compound_class~depth+startime, scales = "free_y", switch="y") +
  scale_fill_gradientn(colours = viridis::viridis(10, alpha = seq(0, 1, length.out=10), direction = -1),
                       limits=c(0, 1), breaks=c(0, 0.25, 0.5, 0.75, 1),
                       labels=c("Fully unlabeled", "", "50% labeled", "", "Fully labeled")) +
  scale_x_discrete(expand = expansion()) +
  scale_y_discrete(expand = expansion()) +
  labs(x=NULL, y=NULL, fill=NULL) +
  theme_bw() +
  theme(panel.spacing.x=unit(0.5, "lines"), 
        panel.spacing.y = unit(0, "lines"),
        axis.text.y = element_blank(),
        axis.ticks.y = element_blank(),
        strip.text.y.left = element_text(angle=0, hjust = 1),
        strip.background.y = element_rect(fill=NA, color=NA),
        panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        legend.position = "top", 
        legend.key.width = unit(1, "null")) +
  guides(
    fill=guide_colorbar(theme=theme(
      legend.frame = element_rect(color = "black"),
      legend.ticks = element_line(color="black"),
      legend.text = ggtext::element_markdown(hjust=c(0, 0, 0.5, 1, 1)))
    )
  )
```


```{r fig 2 MAA labeling patterns}
chosen_maas <- c("Mycosporine-glycine?", "Shinorine?", "Palythine?",
                 "Palythene/Usujirene?", "Also Palythene/Usujirene?", 
                 "Also Porphyra-334?")
labeled_fracs %>%
  filter(compound_name%in%chosen_maas) %>%
  mutate(compound_name=factor(compound_name, levels=chosen_maas)) %>%
  arrange(compound_name) %>%
  mutate(compound_name=str_remove(compound_name, "\\?$")) %>%
  mutate(compound_name=str_replace(compound_name, "Also Palythene/Usujirene", "Palythene or\n usujirene")) %>%
  mutate(compound_name=str_replace(compound_name, "Palythene/Usujirene", "Usujirene or\n palythene")) %>%
  mutate(compound_name=str_remove(compound_name, "Also ")) %>%
  mutate(compound_name=str_replace(compound_name, "-glycine", "-\nglycine")) %>%
  mutate(compound_name=fct_inorder(compound_name)) %>%
  left_join(parametadata, relationship = "many-to-many") %>%
  filter(samp_type=="Smp") %>%
  filter(IS_type=="noIS") %>%
  filter(amendment%in%c("Amm", "Nit")) %>%
  mutate(amendment=factor(amendment, levels=c("Amm", "Nit"), labels=c("+Ammonia", "+Nitrate"))) %>%
  mutate(clock_time=ifelse(startime=="Morn", 6+timepoint_num, 18+timepoint_num)) %>%
  mutate(startime=factor(startime, levels=c("Morn", "Eve"), labels=c("6AM start", "6PM start"))) %>%
  ggplot() +
  annotate("rect", xmin=-Inf, xmax = 6, ymin=-Inf, ymax=Inf, fill="grey80") +
  # annotate("rect", xmin=6, xmax = 18, ymin=-Inf, ymax=Inf, fill="#d0bd65") +
  annotate("rect", xmin=18, xmax = 30, ymin=-Inf, ymax=Inf, fill="grey80") +
  # annotate("rect", xmin=30, xmax = 42, ymin=-Inf, ymax=Inf, fill="#d0bd65") +
  annotate("rect", xmin=42, xmax = Inf, ymin=-Inf, ymax=Inf, fill="grey80") +
  geom_hline(yintercept = c(0.25, 0.5, 0.75, 1), color="grey90") +
  # annotate("rect", xmin=-Inf, xmax=Inf, ymin=-Inf, ymax = Inf, fill="white", alpha=0.3) +
  geom_smooth(aes(x=clock_time, y=labeled_frac, color=startime),
              method=nlsLM, formula="y~a*x^b+d", se = FALSE,
              method.args=list(start=list(a=1, b=2, d=1),
                               control=nls.lm.control(maxiter = 500))) +
  # geom_smooth(aes(x=clock_time, y=labeled_frac, group=startime),
  #             method=glm, formula = "y~x", method.args=list(family="quasibinomial"), 
  #             color="grey10", se=FALSE) +
  # geom_point(aes(x=clock_time, y=labeled_frac, shape=startime), color="black", 
  #            fill="white", size=3) +
  geom_point(aes(x=clock_time, y=labeled_frac, shape=startime, fill=startime),
             color="black", size=2, alpha=0.7) +
  facet_nested(compound_name~amendment) +
  scale_x_continuous(breaks = c(6, 18, 30, 42), labels = c("6AM", "6PM", "6AM", "6PM")) +
  scale_y_continuous(labels = scales::label_percent(),
                     limits = c(0, 1), breaks = c(0, 0.5, 1)) +
  scale_shape_manual(values=c(24, 25), breaks = c("6AM start", "6PM start")) +
  scale_fill_manual(values=c("#f4bb23", "#0b505c"), breaks = c("6AM start", "6PM start"),
                    aesthetics = c("color", "fill")) +
  labs(x=NULL, color=NULL, shape=NULL, fill=NULL, y="Fraction of MAA containing at least one 15N atom") +
  theme_bw() +
  theme(axis.text.y = element_markdown(vjust=c(0, 0.5, 1)),
        axis.title.x = element_blank(),
        legend.position = "inside",
        legend.margin = margin(0.1,0.1,0.1,0.1, unit="lines"),
        legend.position.inside = c(0, 1),
        legend.justification = c(0, 1), 
        legend.background = element_rect(color="black"), 
        legend.direction = "horizontal") +
  guides(shape=guide_legend(override.aes = list(size=3, stroke=1.2, alpha=1, linetype=0)))
```


## Discussion

## Conclusion

## Methods

## Acknowledgements

## Data availability

## References

```{r packages, eval=FALSE}
packages_used <- list.files("..", pattern = "*\\.R$|*\\.Rmd$", recursive = TRUE) %>%
  str_subset("old|scripts", negate=TRUE) %>%
  map(function(file_name){
    v <- readLines(paste0("../", file_name))
    libs <- unique(str_extract(v, "(?<=library\\().*?(?=\\)|,)"))
    refs <- unique(str_extract(v, "[[:alnum:]]*(?=::)"))
    pkgs <- unique(c(na.omit(libs), na.omit(refs)))
  }) %>% unlist() %>% unique()
knitr::write_bib(packages_used[nchar(packages_used)>0], file = "r-packages.bib")
```

<div id="refs"></div>

## Supplement

### Supp fig 1: full heatmap of all compounds and timepoints

```{r suppfig full heatmap}
cmpd_order <- labeled_fracs %>%
  left_join(parametadata, relationship = "many-to-many") %>%
  filter(amendment=="Amm") %>%
  filter(depth=="Surf") %>%
  filter(startime=="Morn") %>%
  summarise(mean_label=mean(labeled_frac, na.rm=TRUE), .by=compound_name) %>%
  arrange(desc(mean_label)) %>%
  pull(compound_name) %>%
  str_remove_all("L-")

heatmap_gp <- labeled_fracs %>%
  left_join(parametadata, relationship = "many-to-many") %>%
  arrange(amendment, depth, timepoint_num, startime) %>%
  mutate(shortname=fct_inorder(shortname)) %>%
  mutate(amendment=factor(amendment, levels=c("Amm", "Nit", "Arg", "GMP"),
                          labels = c("+Ammonia", "+Nitrate", "+Arginine", "+GMP"))) %>%
  mutate(depth=factor(depth, levels=c("Surf", "Deep"), labels=c("25m", "175m"))) %>%
  mutate(compound_name=str_remove_all(compound_name, "^L-")) %>%
  mutate(compound_name=factor(compound_name, cmpd_order)) %>%
  mutate(compound_class=case_when(
    compound_name%in%maa_names~"MAA",
    compound_name%in%aa_names~"Amino\nacid",
    compound_name%in%nucleo_names~"Nucleic\nacid",
    compound_name%in%non_n_names~"N-free",
    compound_name%in%betaine_names~"Betaine",
    TRUE~"Other"
  )) %>%
  mutate(compound_class=factor(compound_class, levels=c("Amino\nacid", "Nucleic\nacid", "MAA", "Betaine", "N-free", "Other"))) %>%
  ggplot() +
  geom_raster(aes(x=timepoint, y=tripl, fill=labeled_frac)) +
  scale_fill_gradientn(colours = viridis::viridis(10, alpha = seq(0, 1, length.out=10), direction = -1), limits=c(0, 1)) +
  scale_y_discrete(expand=expansion()) +
  scale_x_discrete(guide = guide_axis(n.dodge = 3), expand=expansion()) +
  facet_nested(compound_class+compound_name~amendment+depth+startime, scales = "free_x", switch="y", strip=strip_nested(size = "variable")) +
  labs(x="Timepoint", y="Metabolite", fill="Fraction\nlabeled") +
  theme_bw() +
  theme(panel.spacing.x=unit(0.5, "lines"), 
        panel.spacing.y = unit(0, "lines"),
        axis.text.y = element_blank(),
        axis.ticks.y = element_blank(),
        strip.text.y.left = element_text(angle=0, hjust = 1),
        strip.background.y = element_rect(fill=NA, color=NA),
        panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        legend.position = "top", 
        legend.key.width = unit(1, "null")) +
  guides(
    fill=guide_colorbar(theme=theme(
      legend.frame = element_rect(color = "black"),
      legend.ticks = element_line(color="black"),
      legend.text = ggtext::element_markdown(hjust=c(0, 0, 0.5, 1, 1)))
    )
  )

# ggsave(plot = heatmap_gp, "~/../Desktop/para_map.pdf", device = "pdf", 
#        width = 10, height = 12)
```

