---
title: "Untargeted control doc"
author: "William Kumler"
date: '`r Sys.Date()`'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, purl=FALSE)
options(pillar.sigfig=7)
options(readr.num_columns = 0)
options(readr.show_col_types = FALSE)
library(tidyverse)
library(data.table)
library(arrow)
library(xcms)
library(RaMS)

# polarity <- "pos"
polarity <- "neg"
# amendment <- "Amm"
# amendment <- "Nit"
# amendment <- "GMP"
amendment <- "Arg"
IS_type <- "noIS"
# IS_type <- "wIS"

parametadata_all <- read_csv("metadata/parametadata.csv") %>% 
  mutate(startime=factor(startime, levels=c("Morn", "Eve"))) %>%
  mutate(depth=factor(depth, levels=c("Surf", "Deep"))) %>%
  mutate(timepoint=factor(timepoint, levels=paste0("T", c(0,1,3,10,26,73))))
parametadata <- parametadata_all %>%
  filter(polarity==!!polarity) %>%
  filter(amendment==!!amendment) %>%
  filter(IS_type==!!IS_type)

chosen_stans <- read_csv("metadata/all_stans.csv") %>%
  filter(polarity==!!polarity)

output_folder <- paste(amendment, polarity, IS_type, "output", sep = "_") %>%
  paste0("untargeted/", ., "/")
if(!dir.exists(output_folder))dir.create(output_folder)
output_csv_write <- function(object){
  obj_name <- deparse(substitute(object))
  write_csv(object, file = paste0(output_folder, obj_name, ".csv"))
}

xcms_file_data <- parametadata %>%
  mutate(samp_group=paste(amendment, depth, startime, timepoint, sep="-"))

mz_group <- function(mz_vals, ppm){
  group_vec <- numeric(length(mz_vals))
  group_num <- 1L
  init_vec <- mz_vals
  names(init_vec) <- seq_along(init_vec)
  while(length(init_vec)>0){
    mz_i <- init_vec[1]
    err <- mz_i*ppm/1000000
    mz_idxs <- init_vec>mz_i-err & init_vec<mz_i+err
    group_vec[as.numeric(names(mz_idxs)[mz_idxs])] <- group_num
    init_vec <- init_vec[!mz_idxs]
    group_num <- group_num+1L
  }
  group_vec
}
```

# XCMS things

```{r xcms}
parallel_param <- SnowParam(
  workers = parallel::detectCores()-1, 
  tasks = nrow(xcms_file_data), 
  progressbar = TRUE
)

register(BPPARAM = SerialParam(progressbar = TRUE))
msnexp <- readMSData(
  files = xcms_file_data$filepath, 
  pdata = new("NAnnotatedDataFrame", xcms_file_data), 
  msLevel. = 1, 
  mode = "onDisk"
)

cwp <- CentWaveParam(
  ppm = 5, 
  peakwidth = c(20, 80), 
  prefilter = c(3, 1e5), 
  snthresh = 0, 
  verboseColumns = TRUE, 
  extendLengthMSW = TRUE, 
  integrate = 2,
  verboseBetaColumns = TRUE
)
msnexp_withpeaks <- findChromPeaks(msnexp, cwp, BPPARAM=parallel_param)

# mid_file <- xcms_file_data %>%
#   arrange(abs(timestamp-mean(timestamp))) %>%
#   select(filename, timestamp) %>%
#   slice(1) %>%
#   pull(filename)
# mid_file_idx <- which(basename(fileNames(msnexp_filled))==mid_file)
# obp <- ObiwarpParam(binSize = 1, response = 1, distFun = "cor_opt", 
#                     centerSample = mid_file_idx)
# msnexp_rtcor <- adjustRtime(msnexp_withpeaks, obp)

register(BPPARAM = SerialParam(progressbar = TRUE))
pdp <- PeakDensityParam(
  sampleGroups = xcms_file_data$samp_group, 
  bw = 12, 
  minFraction = 0, 
  binSize = 0.001, 
  minSamples = 2
)
msnexp_grouped <- groupChromPeaks(msnexp_withpeaks, pdp)

fpp <- FillChromPeaksParam(ppm = 10)
msnexp_filled <- fillChromPeaks(msnexp_grouped, fpp, BPPARAM=parallel_param)

saveRDS(msnexp_filled, paste0(output_folder, "msnexp_filled.rds"))
```

```{r xcms QC, eval=FALSE}
msnexp_filled <- readRDS(paste0(output_folder, "msnexp_filled.rds"))
```

```{r making peak_data and best_feat_data}
msnexp_filled <- readRDS(paste0(output_folder, "msnexp_filled.rds"))
peak_data_long <- msnexp_filled %>%
  chromPeaks() %>%
  as.data.frame() %>%
  rownames_to_column() %>%
  mutate(peakidx=row_number())
peak_data <- msnexp_filled %>%
  featureDefinitions() %>%
  as.data.frame() %>%
  select(mzmed, rtmed, npeaks, peakidx) %>%
  rownames_to_column("id") %>%
  unnest_longer(peakidx) %>%
  rename_with(~paste0("feat_", .x), .cols = -peakidx) %>%
  dplyr::rename(feature="feat_id") %>%
  left_join(peak_data_long, by = join_by(peakidx)) %>%
  mutate(filename=basename(fileNames(msnexp_filled))[sample]) %>%
  select(feature, feat_mzmed, feat_rtmed, feat_npeaks, filename,
         mz, mzmin, mzmax, rt, rtmin, rtmax, into, sn, beta_cor, beta_snr)
output_csv_write(peak_data)

all_feat_data <- peak_data %>%
  left_join(parametadata) %>%
  filter(samp_type=="Smp") %>%
  group_by(feature) %>%
  summarize(mzmed=unique(feat_mzmed), rtmed=unique(feat_rtmed)/60, n=n(),
            med_cor=median(beta_cor, na.rm=TRUE), 
            med_snr=median(beta_snr, na.rm=TRUE))
output_csv_write(all_feat_data)
# all_feat_data %>%
#   # filter(med_cor>0.75) %>%
#   mutate(n_group=cut(n, breaks = c(0, 2, 10, 40, 60, 62, 100, 130, Inf))) %>%
#   ggplot(aes(label=feature)) +
#   geom_point(aes(x=med_cor, y=med_snr, color=n_group))

# Rescue feats
if(amendment=="Amm"){
  if(polarity=="pos"){
    rescue_feats <- c("FT3015", Allopurinol="FT1319", Hypoxanthine="FT1321",
                      `DMSOP`="FT1688", "Guan from guan"="FT1707", Tyrosine="FT2200",
                      Phosphocholine="FT2228", Trimethyllysine="FT2278",
                      Dexpanthenol="FT2426", Cytidine="FT2792",
                      Mycogly='FT2814', Inosine="FT2960", Guanosine="FT3015")
  } else if(polarity=="neg"){
    rescue_feats <- c()
  }
}
if(amendment=="Nit"){
  if(polarity=="pos"){
    rescue_feats <- c(Creatinine="FT1339", `Homocysteine thiolactone`="FT1444",
                      Leucine="FT1956", Ornithine="FT1980", Lysine="FT2404",
                      THB="FT2706", Lysinebetaineish='FT3317', glucogly="FT4428")

  } else if(polarity=="neg"){
    rescue_feats <- c(Bisulfate="FT0706", "Itaconic acid"="FT1544", 
                      "Salicylic"="FT1841")
  } else {
    stop("Unknown polarity")
  }
}
if(amendment=="GMP"){
  if(polarity=="pos"){
    rescue_feats <- c()
  } else if(polarity=="neg"){
    rescue_feats <- c()
  } else {
    stop("Unknown polarity")
  }
}
if(amendment=="Arg"){
  if(polarity=="pos"){
    rescue_feats <- c("FT0945", "FT1138", "FT1346", "FT1413", "FT1476",
                      "FT1505", "FT1533", "FT1935", "FT1945", "FT2029",
                      "FT2425", "FT2774", "FT2999", "FT3668")
  } else if(polarity=="neg"){
    rescue_feats <- c("FT0790", "FT1022", "FT1031", "FT1387")
  } else {
    stop("Unknown polarity")
  }
}

best_feat_data <- all_feat_data %>%
  filter(med_cor>0.75 | feature%in%rescue_feats) %>%
  select(-med_cor, -med_snr)
output_csv_write(best_feat_data)
```

# Annotation

```{r rescue feats rendering, eval=FALSE}
anno_manu <- readxl::read_excel("untargeted/manual_annotations.xlsx") %>%
  filter(amendment==!!amendment)
all_feat_data <- read_csv(paste0(output_folder, "all_feat_data.csv"))
anno_manu %>%
  filter(str_detect(notes, "[Rr]escue"))
all_feat_data %>%
  filter(mzmed%between%pmppm(138.9701 , 10))
```

```{r plots from mass check and others, eval=FALSE}
best_feat_data %>%
  ggplot() +
  geom_point(aes(x=rtmed, y=mzmed, color=log10(n))) +
  scale_color_viridis_c()

mass_check <- function(mz_i, all_samps=FALSE){
  mass_feats <- best_feat_data %>% 
    filter(mzmed%between%pmppm(mz_i, 5)) %>%
    print()
  if(all_samps){
    chosen_eic <- open_dataset("tmzMLs/pqds") %>%
      filter(polarity==!!polarity) %>%
      filter(amendment==!!amendment) %>%
      filter(mz%between%pmppm(mz_i, 5)) %>%
      filter(rt%between%c(2, 20)) %>%
      dplyr::collect()
  } else {
    chosen_eic <- open_dataset("tmzMLs/pqds") %>%
      filter(polarity==!!polarity) %>%
      filter(amendment==!!amendment) %>%
      filter(samp_type=="Poo" | samp_type=="Std") %>%
      filter(mz%between%pmppm(mz_i, 5)) %>%
      filter(rt%between%c(2, 20)) %>%
      dplyr::collect()
  }
  ggtitle_i <- ifelse(is.null(names(mz_i)), mz_i, names(mz_i))
  chosen_eic %>%
    left_join(parametadata, by = join_by(filename, samp_type, amendment, polarity)) %>%
    mutate(samp_type=str_extract(filename, "Mix\\d|Deep|Surf|Poo|Blk")) %>%
    filter(!str_detect(filename, "Mat")) %>%
    mutate(plot_facet=ifelse(samp_type%in%c("Mix1", "Mix2"), "Mixes", "Samples")) %>%
    ggplot() +
    geom_line(aes(x=rt, y=int, group=filename, color=samp_type)) +
    facet_wrap(~plot_facet, scales = "free_y", ncol=1) +
    geom_vline(aes(xintercept=rtmed), color="black", data = mass_feats) +
    scale_x_continuous(breaks = 2:20) +
    ggtitle(ggtitle_i) +
    theme_bw()
}

best_feat_data %>% slice_sample(n=1) %>% pull(mzmed) %>% mass_check()

mass_check(c("Carn/THB/HMSB"=162.1125))
mass_check(c("ACH/TMAB"=146.1181), all_samps = TRUE)
mass_check(c("Ala/bAla/Sarc"=90.0555))
mass_check(c("Arg"=175.119501))
mass_check(c("Leu/Ile/TMAP"=132.1025))
mass_check(c("15N Ile"=132.1025+0.997))
mass_check(60.04510)
mass_check(c("Ectoine"=143.0821))
mass_check(c("Betonicine"=160.0974))
mass_check(c("Adenine"=136.0623))
mass_check(c("Pyroglut"=130.0504))
mass_check(c("Glutamine"=147.076968))
mass_check(c("Cytosine"=244.093347))
mass_check(c("Proline"=116.0712))
```

```{r annotate}
all_stans <- read_csv("metadata/all_stans.csv") %>%
  mutate(polarity=factor(polarity, levels=c("pos", "neg"))) %>%
  arrange(polarity) %>%
  filter(compound_type!="Internal Standard")
# map(c("Amm", "Nit", "GMP", "Arg"), function(amendment_i){
#   all_stans %>%
#       mutate(amendment=amendment_i) %>%
#       select(amendment, polarity, compound_name, mz, rt, date_added, mix) %>%
#       write_csv("untargeted/anno_template.csv", append = TRUE)
# })
# # Gets copy-pasted into the Excel file manual_annotations.xlsx
# # Then run eicscript.R to render the EICs for each standard and fill it in
# # Afterward, use the "rescue_feats" object above to add those that didn't
# # pass QC for shape or SNR back in

manual_anno <- readxl::read_excel("untargeted/manual_annotations.xlsx")
# manual_anno %>% filter(str_detect(notes, "Unpicked"))
```

```{r check anno}
all_stans <- read_csv("metadata/all_stans.csv") %>%
  filter(polarity==!!polarity) %>%
  filter(compound_type!="Internal Standard")
manual_anno <- readxl::read_excel("untargeted/manual_annotations.xlsx") %>%
  filter(polarity==!!polarity) %>%
  filter(amendment==!!amendment)
best_feat_data <- output_folder %>%
  paste0("best_feat_data.csv") %>%
  read_csv()
mz_rt_check_df <- best_feat_data %>%
  left_join(manual_anno) %>%
  select(feature, compound_name, mzmed, rtmed) %>%
  filter(!is.na(compound_name)) %>%
  left_join(all_stans) %>%
  select(feature, compound_name, mzmed, rtmed, mz, rt)
mz_rt_check_df %>%
  ggplot(aes(label=compound_name)) +
  geom_point(aes(x=rtmed, y=rt)) +
  geom_abline(slope = 1) +
  coord_fixed()
mz_rt_check_df %>%
  ggplot(aes(label=compound_name)) +
  geom_point(aes(x=mzmed, y=mz-mzmed))
```

# Isotope detection

```{r find isotopes (stans only)}
all_stans <- read_csv("metadata/all_stans.csv") %>%
  filter(polarity==!!polarity) %>%
  filter(compound_type!="Internal Standard") %>%
  select(compound_name, formula)
manual_anno <- readxl::read_excel("untargeted/manual_annotations.xlsx") %>%
  filter(polarity==!!polarity) %>%
  filter(amendment==!!amendment) %>%
  select(feature, compound_name)
best_feat_data <- output_folder %>%
  paste0("best_feat_data.csv") %>%
  read_csv() %>%
  left_join(manual_anno) %>%
  left_join(all_stans)
peak_rt_bounds <- output_folder %>%
  paste0("peak_data.csv") %>%
  read_csv() %>%
  select(feature, filename, rtmin, rtmax) %>%
  distinct()
iso_mzs <- best_feat_data %>%
  filter(!is.na(formula)) %>%
  mutate(n_count=str_extract(formula, "N\\d+")) %>%
  mutate(n_count=as.numeric(str_remove(n_count, "N"))) %>%
  mutate(n_count=ifelse(str_detect(formula, "N") & is.na(n_count), 1, n_count)) %>%
  filter(!is.na(n_count)) %>%
  slice(rep(seq(n()), n_count+1)) %>%
  group_by(feature) %>%
  mutate(n_count=1:n()) %>%
  mutate(labeled_mzmed=mzmed+0.997025*(n_count-1)) %>%
  select(compound_name, feature, labeled_mzmed, n_count)
output_csv_write(iso_mzs)

iso_mz_bounds <- iso_mzs %>%
  left_join(peak_rt_bounds, relationship = "many-to-many") %>%
  left_join(parametadata) %>%
  filter(samp_type=="Smp") %>%
  select(compound_name, feature, n_count, labeled_mzmed, filename, rtmin, rtmax)
iso_areas <- iso_mz_bounds %>%
  split(.$filename) %>% 
  imap(function(file_peaks, file_name_i){
    msdata <- open_dataset("tmzMLs/pqds") %>%
      filter(amendment==!!amendment) %>%
      filter(polarity==!!polarity) %>%
      filter(filename==file_name_i) %>%
      dplyr::collect()
    file_peaks %>%
      pmap(function(...){
        row_data <- data.frame(...)
        area <- msdata[mz%between%pmppm(row_data$labeled_mzmed, 10)] %>%
          .[rt%between%c(row_data$rtmin/60, row_data$rtmax/60)] %>%
          .[,sum(int)]
        cbind(row_data, area=area)
      }) %>%
      bind_rows()
  }, .progress=TRUE) %>%
  bind_rows() %>%
  mutate(labeled_n_count=n_count-1) %>%
  select(compound_name, filename, area, labeled_n_count)
output_csv_write(iso_areas)
```

# BMIS and quant

```{r get IS areas from Skyline}
n_only_is <- c("L-Isoleucine, 15N", "AMP, 15N5", "GMP, 15N5", 
               "Nitrate, 15N", "DL-Histidine, 15N")
if(system("untargeted/IS_integrations/SkylineRunner.exe", show.output.on.console = FALSE)){
  # Website = https://skyline.ms/wiki/home/software/Skyline/page.view?name=SkylineInstall_64_21-1&submit=false
  stop("Please grab a copy of SkylineRunner from the website")
}
if(!file.exists("untargeted/IS_integrations/GMP_pos.csv")){
  success_vec <- "untargeted/IS_integrations" %>%
  list.files(pattern = "sky$", full.names = TRUE) %>%
  sapply(skyline_files, function(skyfile){
    polarity <- str_extract(skyfile, "POSITIVE|NEGATIVE")
    polarity <- switch(polarity, "POSITIVE"="pos", "NEGATIVE"="neg")
    amendment <- str_extract(skyfile, "Amm|Nit|GMP|Arg")
  
    sky_cmd <- paste0(
      "untargeted/IS_integrations/SkylineRunner.exe",
      " --in=", skyfile,
      ' --report-name="Molecule Peak Boundaries Modified"', 
      ' --report-file=untargeted/IS_integrations/', amendment, "_", polarity, ".csv"
    )
    failed <- system(sky_cmd)
    if(failed){
      warning(paste("Extraction failed for file", skyfile))
    }
    
    new_csv_name <- paste0("untargeted/IS_integrations/", amendment, "_", polarity, ".csv")
    new_csv <- read.csv(new_csv_name)
    new_csv$polarity <- polarity
    new_csv$amendment <- amendment
    write.csv(new_csv, new_csv_name, row.names = FALSE)
  })
}
IS_areas_all <- "untargeted/IS_integrations/" %>%
  list.files(pattern = "(Amm|Nit|Arg|GMP)_(pos|neg).csv", full.names = TRUE) %>%
  lapply(read.csv) %>%
  do.call(what = "rbind") %>%
  mutate(Area=as.numeric(Area)) %>%
  mutate(Area=ifelse(is.na(Area), 0, Area)) %>%
  select(filename=File.Name, IS_name=Molecule, rtmin=Min.Start.Time,
         rtmax=Max.End.Time, IS_area=Area, polarity, amendment) %>%
  mutate(filename=str_replace(filename, ".raw", ".mzML")) %>%
  filter(!IS_name%in%n_only_is) %>%
  filter(!IS_name=="Succinic acid, 2H4") %>%
  mutate(lead_IS_area=lead(IS_area), lag_IS_area=lag(IS_area)) %>%
  left_join(parametadata_all) %>%
  mutate(IS_area=case_when(
    shortname=="Amm-Surf-Eve-T3-A"~(lead_IS_area+lag_IS_area)/2,
    shortname=="Nit-Deep-Eve-T0-A"~(lead_IS_area+lag_IS_area)/2,
    TRUE~IS_area
  )) %>%
  select(IS_name, filename, IS_area)

# write.csv(IS_areas_all, "untargeted/IS_integrations/IS_areas.csv", row.names = FALSE)

IS_areas_all %>%
  slice(1) %>%
  left_join(parametadata_all)
  filter(amendment==!!amendment) %>%
  arrange(timestamp) %>%
  mutate(shortname=fct_inorder(shortname)) %>%
  ggplot() +
  geom_col(aes(x=shortname, y=IS_area, fill=samp_type), width=1) +
  facet_wrap(~IS_name, scales="free_y", ncol=3)
```

```{r get PheTau areas from raw files}

```



# Isotope visualization

```{r load isotope mzs and areas}
all_stans <- read_csv("metadata/all_stans.csv") %>%
  filter(polarity==!!polarity) %>%
  filter(compound_type!="Internal Standard") %>%
  select(compound_name, formula)
manual_anno <- readxl::read_excel("untargeted/manual_annotations.xlsx") %>%
  filter(polarity==!!polarity) %>%
  filter(amendment==!!amendment) %>%
  select(feature, compound_name)
best_feat_data <- output_folder %>%
  paste0("best_feat_data.csv") %>%
  read_csv() %>%
  left_join(manual_anno) %>%
  left_join(all_stans)
iso_mzs <- read_csv(paste0(output_folder, "iso_mzs.csv"))
iso_areas <- read_csv(paste0(output_folder, "iso_areas.csv"))
```

```{r individual isotope EIC}
single_cmpd_iso_req <- iso_mzs %>%
  filter(compound_name=="Guanine") %>%
  mutate(labeled_mzmed=round(labeled_mzmed, 5)) %>%
  summarise(req_cmd=paste0("mz%between%pmppm(", labeled_mzmed, ", 10)", collapse="|")) %>%
  pull(req_cmd)
full_arrow_req <- paste(
  'open_dataset("tmzMLs/pqds") %>%',
  'filter(amendment==!!amendment) %>%',
  'filter(samp_type=="Smp") %>%',
  'filter(polarity==!!polarity) %>% ',
  'filter(', single_cmpd_iso_req, ') %>% ',
  'dplyr::collect()'
)
single_cmpd_iso_eic <- eval(parse(text=full_arrow_req))

iso_mzs %>%
  filter(compound_name=="Guanine") %>%
  pmap(function(...){
    row_data <- list(...)
    single_cmpd_iso_eic %>%
      filter(mz%between%pmppm(row_data$labeled_mzmed, 10)) %>%
      mutate(n_count=row_data$n_count)
  }) %>%
  bind_rows() %>%
  filter(rt%between%c(7, 9)) %>%
  left_join(parametadata) %>%
  filter(depth=="Surf" & startime=="Morn") %>%
  ggplot() +
  geom_line(aes(x=rt, y=int, group=filename, color=timepoint)) +
  facet_grid(timepoint~n_count) +
  ggtitle("Surface morning spiked samples")
```

```{r individual isotope area plots}
iso_areas <- read_csv(paste0(output_folder, "iso_areas.csv"))

cmpd_name_i <- "Guanine"
single_cmpd_iso_data <- iso_areas %>%
  filter(compound_name==cmpd_name_i) %>%
  left_join(parametadata) %>%
  filter(!is.na(depth)) %>%
  mutate(labeled_n_count=factor(labeled_n_count))

single_cmpd_iso_data %>%
  ggplot() +
  geom_boxplot(aes(x=labeled_n_count, y=area, color=timepoint)) +
  facet_grid(depth~startime, scales="free_y") +
  ggtitle("Raw peak areas across depth and time")

single_cmpd_iso_data %>%
  group_by(depth, startime, labeled_n_count) %>%
  mutate(area=area/sum(area)) %>%
  ggplot() +
  geom_boxplot(aes(x=labeled_n_count, y=area, color=timepoint)) +
  facet_grid(depth~startime) +
  ggtitle("Peak areas normalized to the max within each isotope")

single_cmpd_iso_data %>%
  group_by(depth, startime, labeled_n_count, timepoint) %>%
  summarize(area=median(area)) %>%
  group_by(depth, startime, timepoint) %>%
  mutate(lower_bound=cumsum(lag(area, default = 0))/sum(area)) %>%
  mutate(upper_bound=lead(lower_bound, default = 1)) %>%
  ggplot() +
  geom_ribbon(aes(x=timepoint, ymin=lower_bound, ymax=upper_bound, 
                  fill=labeled_n_count, group=labeled_n_count)) +
  facet_grid(depth~startime) +
  scale_fill_brewer(type = "qual", palette = 3) +
  theme_bw() +
  labs(title = "Median triplicate peak area as a fraction of total for each timepoint",
       x="Timepoint", fill="15N count", 
       y="Fraction of peak area in each isotopologue")

single_cmpd_iso_data %>%
  # group_by(depth, startime, labeled_n_count, timepoint) %>%
  # summarize(area=median(area)) %>%
  ggplot() +
  geom_col(aes(x=timepoint, y=area, fill=labeled_n_count), color="grey50") +
  facet_grid(depth~startime, scales="free_y") +
  scale_fill_brewer(type = "qual", palette = 3) +
  theme_bw() +
  labs(x="Timepoint (hours after spike)", y="Peak area with 15N label",
       fill="Number of\n15N atoms in\nisotopologue",
       title = "Summed peak area by timepoint")
```

```{r isotopes for all targ cmpds}
pdf(paste0(output_folder, "targ_cmpd_mids.pdf"), width = 6, height = 3)
walk(unique(iso_areas$compound_name), function(cmpd_name_i){
  gp <- iso_areas %>%
    filter(compound_name==cmpd_name_i) %>%
    left_join(parametadata, by="filename") %>%
    filter(!is.na(depth)) %>%
    mutate(labeled_n_count=factor(labeled_n_count)) %>%
    group_by(depth, startime, labeled_n_count, timepoint) %>%
    summarize(area=median(area), .groups = "drop") %>%
    group_by(depth, startime, timepoint) %>%
    mutate(lower_bound=cumsum(lag(area, default = 0))/sum(area)) %>%
    mutate(upper_bound=lead(lower_bound, default = 1)) %>%
    ggplot() +
    geom_ribbon(aes(x=timepoint, ymin=lower_bound, ymax=upper_bound, 
                    fill=labeled_n_count, group=labeled_n_count)) +
    facet_grid(startime~depth) +
    scale_fill_brewer(type = "qual", palette = 3) +
    labs(x="Timepoint", fill="15N count", y="Fraction of peak area in\neach isotopologue") +
    theme_bw() +
    ggtitle(cmpd_name_i)
  plot(gp)
}, .progress = TRUE)
dev.off()
```

```{r special classes of isotope trends}
iso_areas <- read_csv(paste0(output_folder, "iso_areas.csv"))
nucleos <- c("Adenine", "Guanine", "Cytosine", "Hypoxanthine", 
             "Adenosine", "Guanosine", "Cytidine", "Inosine",
             "Deoxyadenosine", "Deoxyguanosine?", "Deoxycytidine?")
iso_areas %>%
  filter(compound_name%in%nucleos) %>%
  mutate(compound_name=factor(compound_name, levels=nucleos)) %>%
  left_join(parametadata) %>%
  filter(!is.na(depth)) %>%
  mutate(labeled_n_count=factor(labeled_n_count)) %>%
  filter(depth=="Surf") %>%
  # filter(compound_name=="Guanine") %>%
  group_by(compound_name, labeled_n_count, timepoint) %>%
  summarize(area=median(area)) %>%
  group_by(compound_name, timepoint) %>%
  mutate(lower_bound=cumsum(lag(area, default = 0))/sum(area)) %>%
  mutate(upper_bound=lead(lower_bound, default = 1)) %>%
  ggplot() +
  geom_ribbon(aes(x=timepoint, ymin=lower_bound, ymax=upper_bound, 
                  fill=labeled_n_count, group=labeled_n_count)) +
  facet_wrap(~compound_name, nrow=3) +
  scale_fill_brewer(type = "qual", palette = 3) +
  theme_bw() +
  labs(x="Timepoint (hours after spike)", 
       y="Fraction of peak area with 15N label",
       fill="Number of\n15N atoms in\nisotopologue")

nbases <- c("Adenine", "Guanine", "Cytosine", "Hypoxanthine")
iso_areas %>%
  filter(compound_name%in%nbases) %>%
  mutate(compound_name=factor(compound_name, levels=nbases)) %>%
  left_join(parametadata) %>%
  filter(!is.na(depth)) %>%
  filter(labeled_n_count>0) %>%
  mutate(labeled_n_count=factor(labeled_n_count)) %>%
  filter(timepoint=="T26") %>%
  ggplot() +
  geom_boxplot(aes(x=labeled_n_count, y=area)) +
  ggh4x::facet_grid2(depth~compound_name, scales="free_y", independent = "y")


aminos <- c("Glycine", "L-Alanine", "L-Serine", "L-Proline", 
            "L-Threonine", "L-Leucine", "L-Isoleucine", "L-Tyrosine", 
            "L-Aspartic acid", "L-Asparagine", "beta-Glutamic acid", 
            "L-Glutamine", "L-Methionine", "L-Histidine", "L-Arginine")
iso_areas %>%
  filter(compound_name%in%aminos) %>%
  mutate(compound_name=factor(compound_name, levels=aminos)) %>%
  left_join(parametadata) %>%
  filter(!is.na(depth)) %>%
  mutate(labeled_n_count=factor(labeled_n_count)) %>%
  filter(depth=="Surf") %>%
  group_by(compound_name, labeled_n_count, timepoint) %>%
  summarize(area=median(area)) %>%
  group_by(compound_name, timepoint) %>%
  mutate(lower_bound=cumsum(lag(area, default = 0))/sum(area)) %>%
  mutate(upper_bound=lead(lower_bound, default = 1)) %>%
  ggplot() +
  geom_ribbon(aes(x=timepoint, ymin=lower_bound, ymax=upper_bound, 
                  fill=labeled_n_count, group=labeled_n_count)) +
  facet_wrap(~compound_name, ncol=5) +
  scale_fill_brewer(type = "qual", palette = 3) +
  theme_bw() +
  labs(x="Timepoint (hours after spike)", 
       y="Fraction of peak area with 15N label",
       fill="Number of\n15N atoms in\nisotopologue")

MAAs <- c("Palythine?", "Mycosporine-glycine?", "Asterina-330?", 
          "Shinorine?", "Porphyra-334?", "Mycosporine-2-glycine?")
iso_areas %>%
  filter(compound_name%in%MAAs) %>%
  mutate(compound_name=factor(compound_name, levels=MAAs)) %>%
  left_join(parametadata) %>%
  filter(!is.na(depth)) %>%
  mutate(labeled_n_count=factor(labeled_n_count)) %>%
  filter(depth=="Surf") %>%
  group_by(compound_name, startime, labeled_n_count, timepoint) %>%
  summarize(area=median(area)) %>%
  group_by(compound_name, startime, timepoint) %>%
  mutate(lower_bound=cumsum(lag(area, default = 0))/sum(area)) %>%
  mutate(upper_bound=lead(lower_bound, default = 1)) %>%
  ggplot() +
  geom_ribbon(aes(x=timepoint, ymin=lower_bound, ymax=upper_bound, 
                  fill=labeled_n_count, group=labeled_n_count)) +
  facet_grid(startime~compound_name) +
  scale_fill_brewer(type = "qual", palette = 3) +
  coord_cartesian(ylim = c(0.5, 1)) +
  theme_bw() +
  labs(x="Timepoint (hours after spike)", 
       y="Fraction of peak area with 15N label",
       fill="Number of\n15N atoms in\nisotopologue")

others <- c("Theanine?", "Citrulline", "N-Methyl-L-glutamic acid?", 
            "Ectoine", "5-Hydroxyectoine")
iso_areas %>%
  filter(compound_name%in%others) %>%
  mutate(compound_name=factor(compound_name, levels=others)) %>%
  left_join(parametadata) %>%
  filter(!is.na(depth)) %>%
  mutate(labeled_n_count=factor(labeled_n_count)) %>%
  group_by(compound_name, depth, labeled_n_count, timepoint) %>%
  summarize(area=median(area)) %>%
  group_by(compound_name, depth, timepoint) %>%
  mutate(lower_bound=cumsum(lag(area, default = 0))/sum(area)) %>%
  mutate(upper_bound=lead(lower_bound, default = 1)) %>%
  ggplot() +
  geom_ribbon(aes(x=timepoint, ymin=lower_bound, ymax=upper_bound, 
                  fill=labeled_n_count, group=labeled_n_count)) +
  facet_grid(depth~compound_name) +
  scale_fill_brewer(type = "qual", palette = 3) +
  theme_bw() +
  labs(x="Timepoint (hours after spike)", 
       y="Fraction of peak area with 15N label",
       fill="Number of\n15N atoms in\nisotopologue")
```

```{r special classes of isotope trends alt visualization total area}
chosen_cmpds <- MAAs
iso_areas %>%
  mutate(compound_name=factor(compound_name, levels=chosen_cmpds)) %>%
  drop_na() %>%
  left_join(parametadata) %>%
  filter(!is.na(depth)) %>%
  filter(depth=="Surf") %>%
  mutate(labeled_n_count=factor(labeled_n_count, levels = 5:0)) %>%
  group_by(depth, compound_name, labeled_n_count, timepoint, startime) %>%
  summarize(area=median(area)) %>%
  ggplot() +
  geom_col(aes(x=timepoint, y=area, fill=labeled_n_count)) +
  ggh4x::facet_grid2(startime~compound_name, scales="free_y", independent="y") +
  # facet_grid(startime~compound_name) +
  scale_fill_brewer(type = "qual", palette = 3, direction = -1) +
  theme_bw() +
  theme(legend.position = "none") +
  labs(x="Timepoint (hours after spike)", y="Peak area with 15N label",
       fill="Number of\n15N atoms in\nisotopologue")
```


# Multivariate approaches

```{r overall analysis}
iso_areas <- read_csv(paste0(output_folder, "iso_areas.csv"))
areas_scaled <- iso_areas %>%
  # filter(labeled_n_count>0) %>%
  # filter(labeled_n_count==0) %>%
  left_join(parametadata) %>%
  filter(!is.na(depth)) %>%
  mutate(compound_iso=paste0(compound_name, " 15N", labeled_n_count)) %>%
  arrange(desc(area)) %>%
  select(shortname, compound_iso, area) %>%
  group_by(shortname, compound_iso) %>%
  slice(1) %>%
  ungroup() %>%
  complete(shortname, compound_iso, fill = list(area=0)) %>%
  group_by(compound_iso) %>%
  # mutate(norm_area=(area-min(area))/(max(area)-min(area))) %>%
  # mutate(norm_area=rank(area)) %>%
  mutate(norm_area=scale(area)[,1]) %>%
  ungroup() %>%
  select(shortname, compound_iso, norm_area)

areas_scaled %>%
  pivot_wider(names_from = shortname, values_from = norm_area) %>%
  column_to_rownames("compound_iso") %>%
  data.matrix() %>%
  t() %>%
  prcomp() %>%
  pluck("x") %>%
  as.data.frame() %>%
  rownames_to_column("shortname") %>%
  select(shortname, PC1:PC3) %>%
  left_join(parametadata) %>%
  arrange(timepoint) %>%
  mutate(shortname=fct_inorder(shortname)) %>%
  pivot_longer(starts_with("PC")) %>%
  filter(name%in%paste0("PC", 1:3)) %>%
  ggplot() +
  geom_col(aes(x=shortname, y=value, fill=timepoint)) +
  theme(axis.text.x = element_text(angle=90, hjust=1, vjust=0.5)) +
  facet_wrap(~name, ncol=1)

areas_mat <- areas_scaled %>%
  left_join(parametadata, by="shortname") %>%
  select(compound_iso, shortname, norm_area) %>%
  group_by(compound_iso) %>%
  filter(sum(norm_area==0)<n()*0.9) %>%
  pivot_wider(names_from = "compound_iso", values_from = norm_area) %>%
  column_to_rownames("shortname") %>%
  data.matrix()

adon_expl <- data.frame(shortname=rownames(areas_mat)) %>%
  left_join(parametadata %>% select(shortname, depth, timepoint, startime), by="shortname")
vegan::adonis2(
  areas_mat~timepoint+startime+depth, data = adon_expl, by = "margin", 
  permutations = 999, method = "manhattan")
```

```{r multivar analysis by depth}
multivar_analysis <- areas_scaled %>%
  left_join(parametadata, by="shortname") %>%
  nest(data=-depth) %>%
  mutate(wide_peaks=map(data, function(metab_df){
    metab_df %>%
      select(compound_iso, shortname, norm_area) %>%
      group_by(compound_iso) %>%
      filter(sum(norm_area==0)<n()*0.9) %>%
      pivot_wider(names_from = "compound_iso", values_from = norm_area) %>%
      column_to_rownames("shortname") %>%
      data.matrix()
  })) %>%
  mutate(nmds_output=map(wide_peaks, function(metab_mat){
    # env_vec <- pull(parametadata, timepoint, shortname)[rownames(metab_mat)]
    vegan::metaMDS(metab_mat, k = 2, distance = "manhattan", trace = 0, 
                   autotransform = FALSE, noshare = FALSE, wascores = FALSE)
    # vegan::MDSrotate(env_vec)
  })) %>%
  mutate(nmds_stress=map_dbl(nmds_output, pluck, "stress")) %>%
  mutate(perm_output=map(wide_peaks, function(metab_mat){
    adon_expl <- data.frame(shortname=rownames(metab_mat)) %>%
      left_join(parametadata %>% select(shortname, timepoint, startime), by="shortname")
    vegan::adonis2(
      metab_mat~timepoint+startime, data = adon_expl, by = "margin", 
      permutations = 999, method = "manhattan")
  })) %>%
  mutate(pca_output=map(wide_peaks, prcomp)) %>%
  mutate(hclust_obj=map(wide_peaks, ~hclust(dist(.x))))

multivar_analysis %>%
  mutate(nmds_points=map(nmds_output, function(nmds_output_i){
    nmds_output_i %>% pluck("points") %>% as.data.frame()
  })) %>%
  select(depth, nmds_points) %>%
  unnest_longer(nmds_points, indices_to = "shortname") %>%
  unnest_wider(nmds_points) %>%
  left_join(parametadata %>% distinct(shortname, shortname, timepoint, startime)) %>%
  # mutate(MDS2=ifelse(str_detect(depth,"Deep"), MDS2*-1, MDS2)) %>%
  ggplot(aes(label=shortname)) +
  geom_vline(xintercept = 0) +
  geom_hline(yintercept = 0) +
  geom_point(aes(x=MDS1, y=MDS2, fill=timepoint, shape=startime), color="black", size=4) +
  scale_shape_manual(values = c(22, 23), breaks = c("Morn", "Eve")) +
  facet_wrap(~depth, ncol=1) +
  theme_bw() +
  coord_fixed()

multivar_analysis$perm_output
```


# Univariate followup


