---
title: "figure sandbox"
author: "William Kumler"
date: '`r Sys.Date()`'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, purl=FALSE)
options(pillar.sigfig=7)
options(readr.num_columns = 0)
options(readr.show_col_types = FALSE)
library(tidyverse)
library(data.table)
library(arrow)
library(xcms)
library(RaMS)

polarity <- "pos"
# polarity <- "neg"
amendment <- "Amm"
# amendment <- "Nit"
# amendment <- "GMP"
# amendment <- "Arg"
IS_type <- "noIS"
# IS_type <- "wIS"

parametadata_all <- read_csv("metadata/parametadata.csv") %>% 
  mutate(startime=factor(startime, levels=c("Morn", "Eve"))) %>%
  mutate(depth=factor(depth, levels=c("Surf", "Deep"))) %>%
  mutate(timepoint=factor(timepoint, levels=paste0("T", c(0,1,3,10,26,73))))
parametadata <- parametadata_all %>%
  filter(polarity==!!polarity) %>%
  filter(amendment==!!amendment) %>%
  filter(IS_type==!!IS_type | samp_type=="Std")
manual_typing <- readxl::read_excel("metadata/manual_typing.xlsx") %>%
  mutate(manual_type=ifelse(is.na(manual_type), "Other", manual_type)) %>%
  add_row(compound_name="Thymidine", manual_type="Nucleobases +")
all_stans <- read_csv("metadata/all_stans.csv") %>%
  left_join(manual_typing)

output_folder <- paste(amendment, polarity, IS_type, "output", sep = "_") %>%
  paste0("untargeted/", ., "/")

all_stans <- read_csv("metadata/all_stans.csv") %>%
  filter(polarity==!!polarity) %>%
  filter(compound_type!="Internal Standard") %>%
  select(compound_name, formula)
manual_anno <- readxl::read_excel("untargeted/manual_annotations.xlsx") %>%
  filter(polarity==!!polarity) %>%
  filter(amendment==!!amendment) %>%
  select(feature, compound_name)
best_feat_data <- output_folder %>%
  paste0("best_feat_data.csv") %>%
  read_csv() %>%
  left_join(manual_anno) %>%
  left_join(all_stans)

all_areas <- map(c("pos", "neg"), function(pol_i){
  pol_i_areas <- map(c("Amm", "Nit", "GMP", "Arg"), function(amendment_i){
    file_path <- paste0("G:/My Drive/PARAGON/untargeted/", amendment_i, "_", 
                        pol_i, "_noIS_output/iso_areas.csv")
      read_csv(file_path) %>%
      mutate(amendment=amendment_i)
  }) %>% bind_rows() %>%
    mutate(polarity=pol_i)
}) %>% bind_rows()
all_rfs <- all_areas %>% 
  group_by(amendment, polarity) %>%
  filter(samp_type=="Std") %>%
  filter(labeled_n_count==0) %>%
  left_join(all_stans %>% select(compound_name, mix, conc_um, polarity)) %>%
  mutate(samp_type=str_extract(filename, paste0(mix, "InMatrix|H2OInMatrix"))) %>%
  drop_na() %>%
  mutate(samp_type=str_remove(samp_type, "(?<=Mix)\\d")) %>%
  select(compound_name, samp_type, area, conc_um) %>%
  pivot_wider(names_from=samp_type, values_from = area, values_fn = mean) %>%
  mutate(rf=(MixInMatrix-H2OInMatrix)/conc_um) %>%
  select(compound_name, rf) %>%
  filter(!is.na(rf)) %>%
  filter(rf>0)
all_concs <- all_areas %>%
  right_join(all_rfs) %>%
  mutate(uM_in_vial=area/rf) %>%
  mutate(uM_in_env=(uM_in_vial*(400/1e6))/2) %>%
  mutate(nM_in_env=uM_in_env*1e3) %>%
  select(compound_name, filename, amendment, polarity, labeled_n_count, nM_in_env)
```

# Isotope visualization

## Targeted things

```{r load isotope mzs and areas}
iso_mzs <- read_csv(paste0(output_folder, "iso_mzs.csv"))
iso_areas <- read_csv(paste0(output_folder, "iso_areas.csv")) %>%
  filter(samp_type=="Smp")
```

```{r individual isotope EIC}
single_cmpd_iso_req <- iso_mzs %>%
  filter(compound_name=="Guanine") %>%
  mutate(labeled_mzmed=round(labeled_mzmed, 5)) %>%
  summarise(req_cmd=paste0("mz%between%pmppm(", labeled_mzmed, ", 10)", collapse="|")) %>%
  pull(req_cmd)
full_arrow_req <- paste(
  'open_dataset("tmzMLs/pqds") %>%',
  'filter(amendment==!!amendment) %>%',
  'filter(samp_type=="Smp") %>%',
  'filter(polarity==!!polarity) %>% ',
  'filter(', single_cmpd_iso_req, ') %>% ',
  'dplyr::collect()'
)
single_cmpd_iso_eic <- eval(parse(text=full_arrow_req))

iso_mzs %>%
  filter(compound_name=="Guanine") %>%
  pmap(function(...){
    row_data <- list(...)
    single_cmpd_iso_eic %>%
      filter(mz%between%pmppm(row_data$labeled_mzmed, 10)) %>%
      mutate(n_count=row_data$n_count)
  }) %>%
  bind_rows() %>%
  filter(rt%between%c(7, 9)) %>%
  left_join(parametadata) %>%
  filter(depth=="Surf" & startime=="Morn") %>%
  ggplot() +
  geom_line(aes(x=rt, y=int, group=filename, color=timepoint)) +
  facet_grid(timepoint~n_count) +
  ggtitle("Surface morning spiked samples")
```

```{r individual isotope unknown eic}
unknown_eic <- open_dataset("tmzMLs/pqds") %>%
  filter(amendment=="Amm") %>%
  filter(samp_type=="Smp") %>%
  filter(polarity=="pos") %>%
  filter(mz%between%pmppm(84.04496, 10) | mz%between%pmppm(85.04196, 10)) %>%
  dplyr::collect()
unknown_eic %>%
  mutate(labeled=ifelse(mz<85, "Unlabeled", "Labeled")) %>%
  filter(rt%between%c(10, 13)) %>%
  left_join(parametadata) %>%
  filter(timepoint=="T26") %>%
  ggplot() +
  geom_line(aes(x=rt, y=int, group=filename)) +
  facet_wrap(~labeled, ncol=1, scales="free_y")
unknown_eic %>%
  mutate(labeled=ifelse(mz<85, "Unlabeled", "Labeled")) %>%
  filter(rt%between%c(10, 13)) %>%
  left_join(parametadata) %>%
  arrange(timestamp) %>%
  arrange(timepoint) %>%
  mutate(shortname=fct_inorder(shortname)) %>%
  ggplot() +
  geom_point(aes(x=rt, y=shortname, group=filename, color=log10(int))) +
  facet_wrap(~labeled, ncol=1, scales="free_y") +
  scale_color_viridis_c()
```

```{r individual isotope area plots}
iso_areas <- read_csv(paste0(output_folder, "iso_areas.csv"))

cmpd_name_i <- "Guanine"
single_cmpd_iso_data <- iso_areas %>%
  filter(compound_name==cmpd_name_i) %>%
  left_join(parametadata) %>%
  filter(!is.na(depth)) %>%
  mutate(labeled_n_count=factor(labeled_n_count))

single_cmpd_iso_data %>%
  ggplot() +
  geom_boxplot(aes(x=labeled_n_count, y=area, color=timepoint)) +
  facet_grid(depth~startime, scales="free_y") +
  ggtitle("Raw peak areas across depth and time")

single_cmpd_iso_data %>%
  group_by(depth, startime, labeled_n_count) %>%
  mutate(area=area/sum(area)) %>%
  ggplot() +
  geom_boxplot(aes(x=labeled_n_count, y=area, color=timepoint)) +
  facet_grid(depth~startime) +
  ggtitle("Peak areas normalized to the max within each isotope")

single_cmpd_iso_data %>%
  group_by(depth, startime, labeled_n_count, timepoint) %>%
  summarize(area=median(area)) %>%
  group_by(depth, startime, timepoint) %>%
  mutate(lower_bound=cumsum(lag(area, default = 0))/sum(area)) %>%
  mutate(upper_bound=lead(lower_bound, default = 1)) %>%
  ggplot() +
  geom_ribbon(aes(x=timepoint, ymin=lower_bound, ymax=upper_bound, 
                  fill=labeled_n_count, group=labeled_n_count)) +
  facet_grid(depth~startime) +
  scale_fill_brewer(type = "qual", palette = 3) +
  theme_bw() +
  labs(title = "Median triplicate peak area as a fraction of total for each timepoint",
       x="Timepoint", fill="15N count", 
       y="Fraction of peak area in each isotopologue")

single_cmpd_iso_data %>%
  # group_by(depth, startime, labeled_n_count, timepoint) %>%
  # summarize(area=median(area)) %>%
  ggplot() +
  geom_col(aes(x=timepoint, y=area, fill=labeled_n_count), color="grey50") +
  facet_grid(depth~startime, scales="free_y") +
  scale_fill_brewer(type = "qual", palette = 3) +
  theme_bw() +
  labs(x="Timepoint (hours after spike)", y="Peak area with 15N label",
       fill="Number of\n15N atoms in\nisotopologue",
       title = "Summed peak area by timepoint")
```

```{r isotopes for all targ cmpds}
pdf(paste0(output_folder, "targ_cmpd_mids.pdf"), width = 6, height = 3)
walk(unique(iso_areas$compound_name), function(cmpd_name_i){
  gp <- iso_areas %>%
    filter(compound_name==cmpd_name_i) %>%
    left_join(parametadata, by="filename") %>%
    filter(!is.na(depth)) %>%
    mutate(labeled_n_count=factor(labeled_n_count)) %>%
    group_by(depth, startime, labeled_n_count, timepoint) %>%
    summarize(area=median(area), .groups = "drop") %>%
    group_by(depth, startime, timepoint) %>%
    mutate(lower_bound=cumsum(lag(area, default = 0))/sum(area)) %>%
    mutate(upper_bound=lead(lower_bound, default = 1)) %>%
    ggplot() +
    geom_ribbon(aes(x=timepoint, ymin=lower_bound, ymax=upper_bound, 
                    fill=labeled_n_count, group=labeled_n_count)) +
    facet_grid(startime~depth) +
    scale_fill_brewer(type = "qual", palette = 3) +
    labs(x="Timepoint", fill="15N count", y="Fraction of peak area in\neach isotopologue") +
    theme_bw() +
    ggtitle(cmpd_name_i)
  plot(gp)
}, .progress = TRUE)
dev.off()
```

```{r special classes of isotope trends}
iso_areas <- read_csv(paste0(output_folder, "iso_areas.csv"))
nucleos <- c("Adenine", "Guanine", "Cytosine", "Hypoxanthine", 
             "Adenosine", "Guanosine", "Cytidine", "Inosine",
             "Deoxyadenosine", "Deoxyguanosine?", "Deoxycytidine?")
iso_areas %>%
  filter(compound_name%in%nucleos) %>%
  mutate(compound_name=factor(compound_name, levels=nucleos)) %>%
  left_join(parametadata) %>%
  filter(!is.na(depth)) %>%
  mutate(labeled_n_count=factor(labeled_n_count)) %>%
  filter(depth=="Surf") %>%
  # filter(compound_name=="Guanine") %>%
  group_by(compound_name, labeled_n_count, timepoint) %>%
  summarize(area=median(area)) %>%
  group_by(compound_name, timepoint) %>%
  mutate(lower_bound=cumsum(lag(area, default = 0))/sum(area)) %>%
  mutate(upper_bound=lead(lower_bound, default = 1)) %>%
  ggplot() +
  geom_ribbon(aes(x=timepoint, ymin=lower_bound, ymax=upper_bound, 
                  fill=labeled_n_count, group=labeled_n_count)) +
  facet_wrap(~compound_name, nrow=3) +
  scale_fill_brewer(type = "qual", palette = 3) +
  theme_bw() +
  labs(x="Timepoint (hours after spike)", 
       y="Fraction of peak area with 15N label",
       fill="Number of\n15N atoms in\nisotopologue")

nbases <- c("Adenine", "Guanine", "Cytosine", "Hypoxanthine")
iso_areas %>%
  filter(compound_name%in%nbases) %>%
  mutate(compound_name=factor(compound_name, levels=nbases)) %>%
  left_join(parametadata) %>%
  filter(!is.na(depth)) %>%
  filter(labeled_n_count>0) %>%
  mutate(labeled_n_count=factor(labeled_n_count)) %>%
  filter(timepoint=="T26") %>%
  ggplot() +
  geom_boxplot(aes(x=labeled_n_count, y=area)) +
  ggh4x::facet_grid2(depth~compound_name, scales="free_y", independent = "y")


aminos <- c("Glycine", "L-Alanine", "L-Serine", "L-Proline", 
            "L-Threonine", "L-Leucine", "L-Isoleucine", "L-Tyrosine", 
            "L-Aspartic acid", "L-Asparagine", "beta-Glutamic acid", 
            "L-Glutamine", "L-Methionine", "L-Histidine", "L-Arginine")
iso_areas %>%
  filter(compound_name%in%aminos) %>%
  mutate(compound_name=factor(compound_name, levels=aminos)) %>%
  left_join(parametadata) %>%
  filter(!is.na(depth)) %>%
  mutate(labeled_n_count=factor(labeled_n_count)) %>%
  filter(depth=="Surf") %>%
  group_by(compound_name, labeled_n_count, timepoint) %>%
  summarize(area=median(area)) %>%
  group_by(compound_name, timepoint) %>%
  mutate(lower_bound=cumsum(lag(area, default = 0))/sum(area)) %>%
  mutate(upper_bound=lead(lower_bound, default = 1)) %>%
  ggplot() +
  geom_ribbon(aes(x=timepoint, ymin=lower_bound, ymax=upper_bound, 
                  fill=labeled_n_count, group=labeled_n_count)) +
  facet_wrap(~compound_name, ncol=5) +
  scale_fill_brewer(type = "qual", palette = 3) +
  theme_bw() +
  labs(x="Timepoint (hours after spike)", 
       y="Fraction of peak area with 15N label",
       fill="Number of\n15N atoms in\nisotopologue")

MAAs <- c("Palythine?", "Mycosporine-glycine?", "Asterina-330?", 
          "Shinorine?", "Porphyra-334?", "Mycosporine-2-glycine?")
iso_areas %>%
  filter(compound_name%in%MAAs) %>%
  mutate(compound_name=factor(compound_name, levels=MAAs)) %>%
  left_join(parametadata) %>%
  filter(!is.na(depth)) %>%
  mutate(labeled_n_count=factor(labeled_n_count)) %>%
  filter(depth=="Surf") %>%
  group_by(compound_name, startime, labeled_n_count, timepoint) %>%
  summarize(area=median(area)) %>%
  group_by(compound_name, startime, timepoint) %>%
  mutate(lower_bound=cumsum(lag(area, default = 0))/sum(area)) %>%
  mutate(upper_bound=lead(lower_bound, default = 1)) %>%
  ggplot() +
  geom_ribbon(aes(x=timepoint, ymin=lower_bound, ymax=upper_bound, 
                  fill=labeled_n_count, group=labeled_n_count)) +
  facet_grid(startime~compound_name) +
  scale_fill_brewer(type = "qual", palette = 3) +
  coord_cartesian(ylim = c(0.5, 1)) +
  theme_bw() +
  labs(x="Timepoint (hours after spike)", 
       y="Fraction of peak area with 15N label",
       fill="Number of\n15N atoms in\nisotopologue")

others <- c("Theanine?", "Citrulline", "N-Methyl-L-glutamic acid?", 
            "Ectoine", "5-Hydroxyectoine")
iso_areas %>%
  filter(compound_name%in%others) %>%
  mutate(compound_name=factor(compound_name, levels=others)) %>%
  left_join(parametadata) %>%
  filter(!is.na(depth)) %>%
  mutate(labeled_n_count=factor(labeled_n_count)) %>%
  group_by(compound_name, depth, labeled_n_count, timepoint) %>%
  summarize(area=median(area)) %>%
  group_by(compound_name, depth, timepoint) %>%
  mutate(lower_bound=cumsum(lag(area, default = 0))/sum(area)) %>%
  mutate(upper_bound=lead(lower_bound, default = 1)) %>%
  ggplot() +
  geom_ribbon(aes(x=timepoint, ymin=lower_bound, ymax=upper_bound, 
                  fill=labeled_n_count, group=labeled_n_count)) +
  facet_grid(depth~compound_name) +
  scale_fill_brewer(type = "qual", palette = 3) +
  theme_bw() +
  labs(x="Timepoint (hours after spike)", 
       y="Fraction of peak area with 15N label",
       fill="Number of\n15N atoms in\nisotopologue")
```

```{r special classes of isotope trends alt visualization total area}
chosen_cmpds <- MAAs
iso_areas %>%
  mutate(compound_name=factor(compound_name, levels=chosen_cmpds)) %>%
  drop_na() %>%
  left_join(parametadata) %>%
  filter(!is.na(depth)) %>%
  filter(depth=="Surf") %>%
  mutate(labeled_n_count=factor(labeled_n_count, levels = 5:0)) %>%
  group_by(depth, compound_name, labeled_n_count, timepoint, startime) %>%
  summarize(area=median(area)) %>%
  ggplot() +
  geom_col(aes(x=timepoint, y=area, fill=labeled_n_count)) +
  ggh4x::facet_grid2(startime~compound_name, scales="free_y", independent="y") +
  # facet_grid(startime~compound_name) +
  scale_fill_brewer(type = "qual", palette = 3, direction = -1) +
  theme_bw() +
  theme(legend.position = "none") +
  labs(x="Timepoint (hours after spike)", y="Peak area with 15N label",
       fill="Number of\n15N atoms in\nisotopologue")
```

```{r nested geom_tile plot overview multicompound comparison}
library(ggh4x)
iso_areas %>%
  filter(!str_detect(filename, "Blk")) %>%
  filter(compound_name%in%c("Guanine", "Guanosine", "Adenine", "Adenosine",
                            "Cytosine", "Cytidine", "Thymine", "Thymidine",
                            "Uracil", "Uridine", "Hypoxanthine", "Inosine")) %>%
  left_join(parametadata_all) %>%
  group_by(compound_name, timepoint, depth, startime, tripl) %>%
  mutate(area=area/sum(area)) %>%
  ggplot() +
  geom_tile(aes(x=tripl, y=labeled_n_count, fill=area)) +
  ggh4x::facet_nested(compound_name~depth+startime+timepoint, space = "free_y", scales = "free_y") +
  scale_fill_viridis_c(labels=scales::label_percent()) +
  labs(y="Number of labeled nitrogens", fill="Fraction\nof total\npeak area") +
  theme(axis.text.x = element_blank(), axis.title.x = element_blank(),
        axis.ticks.x=element_blank())

iso_areas %>%
  filter(!str_detect(filename, "Blk")) %>%
  filter(compound_name%in%c("Guanine", "Guanosine", "Adenine", "Adenosine")) %>%
  left_join(parametadata_all) %>%
  ggplot() +
  geom_boxplot(aes(x=factor(labeled_n_count), y=area, color=timepoint)) +
  ggh4x::facet_nested(compound_name~depth+startime, scales="free_y", independent = "y") +
  labs(x="Number of labeled nitrogens", y="Peak area", color="Timepoint") +
  theme_bw()

iso_areas %>%
  filter(!str_detect(filename, "Blk")) %>%
  filter(compound_name%in%c("Guanine", "Guanosine", "Adenine", "Adenosine")) %>%
  left_join(parametadata_all) %>%
  group_by(compound_name, depth, startime, timepoint, labeled_n_count) %>%
  summarise(med_area=median(area), .groups = "drop_last") %>%
  mutate(med_area=med_area/sum(med_area)) %>%
  mutate(labeled_n_count=factor(labeled_n_count, levels=5:0)) %>%
  ggplot() +
  geom_col(aes(x=timepoint, y=med_area, fill=labeled_n_count), position = "stack") +
  facet_nested(compound_name~depth+startime) +
  scale_y_continuous(labels=scales::percent_format()) +
  scale_fill_viridis_d(direction = -1) +
  labs(x="Timepoint", y="Isotope distribution", fill="Number of\nlabeled\nnitrogens")
```


## Among good peak isotope pairs

```{r make iso_pairs}
peak_data <- read_csv(paste0(output_folder, "peak_data.csv"))
iso_pairs <- read_csv(paste0(output_folder, "iso_pairs.csv"))

clean_iso_data <- iso_pairs %>% 
  select(feature, feature_iso) %>%
  left_join(peak_data %>% select(feature, filename, into), by="feature") %>%
  left_join(parametadata, by="filename") %>%
  filter(samp_type=="Smp") %>%
  filter(!str_detect(shortname, "Blk")) %>%
  left_join(peak_data %>% select(feature, filename, into), 
            by=c(feature_iso="feature", "filename")) %>%
  mutate(label_ratio=into.y/into.x) %>%
  group_by(feature, feature_iso, untripl) %>%
  mutate(label_ratio=ifelse(is.na(label_ratio), median(label_ratio, na.rm=TRUE), label_ratio)) %>%
  group_by(feature, feature_iso, depth) %>%
  # mutate(label_ratio=rank(label_ratio)) %>%
  ungroup() %>%
  select(feature, feature_iso, shortname, label_ratio, timepoint, timepoint_num, depth, startime)
```

```{r render all iso_pairs ratios}
pdf(paste0(output_folder, "iso_untarg_ratios.pdf"), width = 6, height = 6)
pb <- txtProgressBar(max = nrow(iso_pairs), style = 3)
for(ind_i in seq_len(nrow(iso_pairs))){
  setTxtProgressBar(pb, ind_i)
  iso_gp <- iso_pairs %>% 
    slice(ind_i) %>%
    select(feature, feature_iso) %>%
    left_join(peak_data %>% select(feature, filename, into), by="feature") %>%
    left_join(parametadata, by="filename") %>%
    filter(samp_type=="Smp") %>%
    filter(!str_detect(shortname, "Blk")) %>%
    left_join(peak_data %>% select(feature, filename, into), by=c(feature_iso="feature", "filename")) %>%
    mutate(label_ratio=into.y/into.x) %>%
    group_by(untripl) %>%
    mutate(label_ratio=ifelse(is.na(label_ratio), median(label_ratio, na.rm=TRUE), label_ratio)) %>%
    ungroup() %>%
    arrange(depth, startime, timepoint) %>%
    mutate(shortname=fct_inorder(shortname)) %>%
    ggplot() +
    geom_col(aes(x=label_ratio, y=shortname, fill=timepoint)) +
    scale_x_log10() +
    scale_fill_discrete(drop=FALSE) +
    facet_wrap(~depth, ncol=1, scales="free") +
    ggtitle(paste0(iso_pairs$feature[ind_i], ": ", 
                  ifelse(is.na(iso_pairs$compound_name[ind_i]), 
                         round(iso_pairs$mzmed[ind_i], 5), 
                         iso_pairs$compound_name[ind_i])))
  print(iso_gp)
}
close(pb)
dev.off()
```

```{r make clean_iso_data}
clean_iso_data %>%
  filter(feature%in%c("FT0085", "FT0239", "FT0240")) %>%
  ggplot(aes(x=timepoint_num, y=label_ratio)) +
  geom_smooth(method=minpack.lm::nlsLM, color="black", formula="y~a*x^b+d", se = FALSE, 
              method.args=list(start=list(a=1, b=2, d=1))) +
  geom_point(aes(color=timepoint, shape=startime)) +
  # geom_boxplot(aes(color=timepoint, group=timepoint_num)) +
  ggh4x::facet_grid2(depth~feature, scales="free_y", independent = "y")
```

```{r manual curve log/lin/exp classification}
shape_classes <- clean_iso_data %>%
  # filter(depth=="Surf") %>%
  # filter(feature%in%c("FT0085", "FT0239", "FT0240")) %>%
  nest(data=-c(feature, depth)) %>%
  mutate(lin_test=map(data, ~broom::tidy(lm(.x$label_ratio~.x$timepoint_num)))) %>%
  mutate(exp_test=map(data, ~broom::tidy(lm(log(.x$label_ratio)~.x$timepoint_num)))) %>%
  mutate(log_test=map(data, ~broom::tidy(lm(exp(.x$label_ratio)~.x$timepoint_num)))) %>%
  unnest(ends_with("test"), names_sep = "_") %>%
  filter(lin_test_term==".x$timepoint_num") %>%
  select(feature, depth, data, ends_with("p.value")) %>%
  pivot_longer(ends_with("p.value")) %>%
  group_by(feature, depth) %>%
  arrange(value) %>%
  slice(1) %>%
  ungroup() %>%
  mutate(name=str_remove(name, "_test_p.value")) %>%
  select(feature, depth, cluster=name)
shape_classes %>%
  left_join(clean_iso_data %>% select(feature, label_ratio, shortname, timepoint, depth)) %>%
  group_by(feature) %>%
  mutate(label_ratio=scale(label_ratio)[,1]) %>%
  ungroup() %>%
  group_by(cluster, shortname, timepoint, depth) %>%
  summarise(label_ratio=mean(label_ratio, na.rm=TRUE)) %>%
  ggplot(aes(x=timepoint, y=label_ratio, color=timepoint)) +
  geom_hline(yintercept = 0) +
  geom_boxplot() +
  facet_grid(depth~cluster)
shape_classes %>%
  left_join(iso_anno) %>%
  filter(!is.na(compound_name)) %>%
  print(n=Inf)
```

```{r kmeans isotope curve classification}
kmeans_obj <- clean_iso_data %>%
  select(feature, shortname, label_ratio) %>%
  complete(feature, shortname) %>%
  group_by(feature) %>%
  filter(sum(is.na(label_ratio))==0) %>%
  mutate(label_ratio=scale(label_ratio)[,1]) %>%
  ungroup() %>%
  pivot_wider(names_from = shortname, values_from = label_ratio) %>%
  column_to_rownames("feature") %>%
  kmeans(centers = 3)
data.frame(cluster=kmeans_obj$cluster) %>%
  mutate(cluster=paste0("Cluster ", cluster, ", n=", kmeans_obj$size[cluster])) %>%
  rownames_to_column("feature") %>%
  left_join(clean_iso_data %>% select(feature, label_ratio, shortname, timepoint, depth)) %>%
  group_by(feature) %>%
  mutate(label_ratio=scale(label_ratio)[,1]) %>%
  ungroup() %>%
  # group_by(cluster, shortname, timepoint, depth) %>%
  # summarise(label_ratio=mean(label_ratio)) %>%
  ggplot(aes(x=timepoint, y=label_ratio, color=timepoint)) +
  geom_hline(yintercept = 0) +
  geom_boxplot() +
  facet_grid(depth~cluster)
```

```{r nls curve classification w minpack.lm package}
library(minpack.lm)
clean_iso_data %>%
  complete(feature, shortname) %>%
  mutate(untripl=str_remove(shortname, "-[A-C]")) %>%
  group_by(feature) %>%
  filter(sum(is.na(label_ratio))==0) %>%
  nest(data=-c(feature, depth)) %>%
  mutate(nls_test=map(data, ~broom::tidy(nlsLM(label_ratio~a*timepoint_num^b+d, 
                                             start = list(a=1, b=2, d=1), data=.x,
                                             control=nls.lm.control(maxiter = 500))))) %>%
  unnest(nls_test) %>%
  select(feature, depth, data, term, estimate) %>%
  pivot_wider(names_from = term, values_from = estimate) %>%
  # left_join(shape_classes) %>%
  mutate(a_sign=factor(ifelse(a<0, "neg", "pos"), levels=c("pos", "neg"))) %>%
  mutate(a=abs(a)) %>%
  left_join(iso_pairs %>% select(feature, compound_name) %>% drop_na()) %>%
  mutate(feature=ifelse(is.na(compound_name), feature, compound_name)) %>%
  ggplot() +
  geom_hline(yintercept = 0) +
  geom_vline(xintercept = 1) +
  geom_text(aes(x=b, y=a, label=feature, color=depth), hjust=0.2) +
  annotate("label", x=1, y=Inf, hjust=0, vjust=1, label="Exponential", label.r=unit(0, "in")) +
  annotate("label", x=1, y=Inf, hjust=1, vjust=1, label="Logarithmic", label.r=unit(0, "in")) +
  scale_y_log10() +
  facet_wrap(~a_sign, ncol=1, scales = "free_y")
ggsave(filename = paste0(output_folder, "nls_coefs.pdf"), device = "pdf", 
       width = 10, height = 10, units = "in")

clean_iso_data %>%
  left_join(iso_pairs %>% select(feature, compound_name) %>% drop_na()) %>%
  mutate(feature=ifelse(is.na(compound_name), feature, compound_name)) %>%
  ggplot(aes(x=timepoint_num, y=label_ratio)) +
  geom_hline(yintercept = 0) +
  geom_smooth(method="nlsLM", color="black", formula="y~a*x^b+d", se = FALSE, 
              method.args=list(start=list(a=1, b=2, d=1))) +
  geom_point(aes(color=timepoint, shape=startime)) +
  ggh4x::facet_grid2(depth~feature, scales="free_y", independent = "y")
ggsave(filename = paste0(output_folder, "nls_fits.pdf"), device = "pdf",
       width = 80, height = 4, units = "in", limitsize = FALSE)
```

## For all untargeted compounds from isotope envelopes

```{r}
raw_iso_envelopes <- read_csv(paste0(output_folder, "raw_iso_envelopes.csv"))

label_frac <- raw_iso_envelopes %>%
  group_by(feature, iso_count) %>%
  mutate(med_corr=median(corr, na.rm=TRUE)) %>%
  filter(med_corr>0.8) %>%
  select(feature, filename, iso_count, area) %>%
  # ggplot() + geom_boxplot(aes(x=iso_count, y=area, group=iso_count))
  mutate(label_type=ifelse(iso_count==0, "unlabeled", "labeled")) %>%
  select(-iso_count) %>%
  group_by(feature, filename, label_type) %>%
  summarise(area=sum(area, na.rm=TRUE)) %>%
  pivot_wider(names_from=label_type, values_from = area) %>%
  mutate(labeled_ratio=labeled/(unlabeled+labeled)) %>%
  left_join(parametadata) %>%
  drop_na()
label_frac %>%
  # filter(feature=="FT0915") %>%
  # filter(feature=="FT1705") %>%
  filter(feature=="FT0239") %>%
  ggplot() + 
  geom_hline(yintercept = 0) +
  geom_vline(xintercept = 0) +
  geom_abline(slope = 1, intercept = 0) +
  geom_point(aes(x=labeled, y=unlabeled, color=timepoint, shape=startime)) +
  facet_wrap(~depth, ncol=1, scales="free")
label_frac %>%
  filter(feature=="FT0239") %>%
  ggplot() +
  geom_hline(yintercept = 0) +
  geom_point(aes(x=timepoint, y=labeled_ratio, color=timepoint, shape=startime)) +
  facet_wrap(~depth, ncol=1, scales="free")
```


# Multivariate approaches

```{r overall analysis}
iso_areas <- read_csv(paste0(output_folder, "iso_areas.csv"))
areas_scaled <- iso_areas %>%
  # filter(labeled_n_count>0) %>%
  # filter(labeled_n_count==0) %>%
  left_join(parametadata) %>%
  filter(!is.na(depth)) %>%
  mutate(compound_iso=paste0(compound_name, " 15N", labeled_n_count)) %>%
  arrange(desc(area)) %>%
  select(shortname, compound_iso, area) %>%
  group_by(shortname, compound_iso) %>%
  slice(1) %>%
  ungroup() %>%
  complete(shortname, compound_iso, fill = list(area=0)) %>%
  group_by(compound_iso) %>%
  # mutate(norm_area=(area-min(area))/(max(area)-min(area))) %>%
  # mutate(norm_area=rank(area)) %>%
  mutate(norm_area=scale(area)[,1]) %>%
  ungroup() %>%
  select(shortname, compound_iso, norm_area)

areas_scaled %>%
  pivot_wider(names_from = shortname, values_from = norm_area) %>%
  column_to_rownames("compound_iso") %>%
  data.matrix() %>%
  t() %>%
  prcomp() %>%
  pluck("x") %>%
  as.data.frame() %>%
  rownames_to_column("shortname") %>%
  select(shortname, PC1:PC3) %>%
  left_join(parametadata) %>%
  arrange(timepoint) %>%
  mutate(shortname=fct_inorder(shortname)) %>%
  pivot_longer(starts_with("PC")) %>%
  filter(name%in%paste0("PC", 1:3)) %>%
  ggplot() +
  geom_col(aes(x=shortname, y=value, fill=timepoint)) +
  theme(axis.text.x = element_text(angle=90, hjust=1, vjust=0.5)) +
  facet_wrap(~name, ncol=1)

areas_mat <- areas_scaled %>%
  left_join(parametadata, by="shortname") %>%
  select(compound_iso, shortname, norm_area) %>%
  group_by(compound_iso) %>%
  filter(sum(norm_area==0)<n()*0.9) %>%
  pivot_wider(names_from = "compound_iso", values_from = norm_area) %>%
  column_to_rownames("shortname") %>%
  data.matrix()

adon_expl <- data.frame(shortname=rownames(areas_mat)) %>%
  left_join(parametadata %>% select(shortname, depth, timepoint, startime), by="shortname")
vegan::adonis2(
  areas_mat~timepoint+startime+depth, data = adon_expl, by = "margin", 
  permutations = 999, method = "manhattan")
```

```{r multivar analysis by depth}
multivar_analysis <- areas_scaled %>%
  left_join(parametadata, by="shortname") %>%
  nest(data=-depth) %>%
  mutate(wide_peaks=map(data, function(metab_df){
    metab_df %>%
      select(compound_iso, shortname, norm_area) %>%
      group_by(compound_iso) %>%
      filter(sum(norm_area==0)<n()*0.9) %>%
      pivot_wider(names_from = "compound_iso", values_from = norm_area) %>%
      column_to_rownames("shortname") %>%
      data.matrix()
  })) %>%
  mutate(nmds_output=map(wide_peaks, function(metab_mat){
    # env_vec <- pull(parametadata, timepoint, shortname)[rownames(metab_mat)]
    vegan::metaMDS(metab_mat, k = 2, distance = "manhattan", trace = 0, 
                   autotransform = FALSE, noshare = FALSE, wascores = FALSE)
    # vegan::MDSrotate(env_vec)
  })) %>%
  mutate(nmds_stress=map_dbl(nmds_output, pluck, "stress")) %>%
  mutate(perm_output=map(wide_peaks, function(metab_mat){
    adon_expl <- data.frame(shortname=rownames(metab_mat)) %>%
      left_join(parametadata %>% select(shortname, timepoint, startime), by="shortname")
    vegan::adonis2(
      metab_mat~timepoint+startime, data = adon_expl, by = "margin", 
      permutations = 999, method = "manhattan")
  })) %>%
  mutate(pca_output=map(wide_peaks, prcomp)) %>%
  mutate(hclust_obj=map(wide_peaks, ~hclust(dist(.x))))

multivar_analysis %>%
  mutate(nmds_points=map(nmds_output, function(nmds_output_i){
    nmds_output_i %>% pluck("points") %>% as.data.frame()
  })) %>%
  select(depth, nmds_points) %>%
  unnest_longer(nmds_points, indices_to = "shortname") %>%
  unnest_wider(nmds_points) %>%
  left_join(parametadata %>% distinct(shortname, shortname, timepoint, startime)) %>%
  # mutate(MDS2=ifelse(str_detect(depth,"Deep"), MDS2*-1, MDS2)) %>%
  ggplot(aes(label=shortname)) +
  geom_vline(xintercept = 0) +
  geom_hline(yintercept = 0) +
  geom_point(aes(x=MDS1, y=MDS2, fill=timepoint, shape=startime), color="black", size=4) +
  scale_shape_manual(values = c(22, 23), breaks = c("Morn", "Eve")) +
  facet_wrap(~depth, ncol=1) +
  theme_bw() +
  coord_fixed()

multivar_analysis$perm_output
```

```{r logistic curve fitting contour plot and curve fitting}
glm_coef_data <- all_concs %>%
  left_join(parametadata_all) %>%
  filter(amendment=="Amm") %>%
  filter(samp_type=="Smp") %>%
  filter(!str_detect(filename, "Blk")) %>%
  mutate(label_type=ifelse(labeled_n_count==0, "Unlabeled", "Labeled")) %>%
  select(compound_name, filename, label_type, nM_in_env, timepoint_num, depth, startime) %>%
  pivot_wider(names_from = label_type, values_from=nM_in_env, values_fn = sum) %>%
  mutate(frac_labeled=Labeled/(Labeled+Unlabeled)) %>%
  nest(data=-c(compound_name, depth)) %>%
  mutate(nls_test=map(data, ~broom::tidy(glm(.x$frac_labeled~.x$timepoint_num, family=quasibinomial)))) %>%
  unnest(nls_test) %>%
  select(compound_name, depth, data, term, estimate) %>%
  pivot_wider(names_from = term, values_from = estimate) %>%
  dplyr::rename(intercept=`(Intercept)`, slope=`.x$timepoint_num`) %>%
  mutate(intercept=1-(exp(-intercept)/(1+exp(-intercept)))) %>%
  left_join(manual_typing)
```

```{r kmeans clustering of isotope signals}
frac_labeled_df <- all_areas %>%
  left_join(parametadata_all) %>%
  filter(amendment=="Amm") %>%
  filter(samp_type=="Smp") %>%
  filter(!str_detect(filename, "Blk")) %>%
  filter(polarity=="pos") %>%
  mutate(label_type=ifelse(labeled_n_count==0, "Unlabeled", "Labeled")) %>%
  select(compound_name, shortname, label_type, area, timepoint_num, depth, startime) %>%
  pivot_wider(names_from = label_type, values_from=area, values_fn = sum) %>%
  mutate(frac_labeled=Labeled/(Labeled+Unlabeled)) %>%
  ungroup() %>%
  arrange(depth, startime, timepoint_num) %>%
  mutate(shortname=fct_inorder(shortname))
  
frac_labeled_df %>%
  filter(compound_name=="L-Glutamine") %>%
  ggplot() +
  geom_point(aes(x=timepoint_num, y=frac_labeled)) +
  facet_grid(depth~startime)

frac_mat <- frac_labeled_df %>%
  select(compound_name, shortname, frac_labeled) %>%
  pivot_wider(names_from=shortname, values_from=frac_labeled) %>%
  mutate(across(everything(), function(x)ifelse(is.na(x), 0, x))) %>%
  # filter(compound_name=="L-Glutamine") %>%
  # filter(is.na(`210916_Smp_Amm-Deep-Eve-T0-A-noIS-pos.mzML`)) %>%
  column_to_rownames("compound_name")

# heatmaply::heatmaply(frac_mat, Colv=FALSE)
kmeans_obj <- kmeans(frac_mat, centers = 4)
mapping <- `names<-`(1:6, order(kmeans_obj$size, decreasing = TRUE))
old_names <- names(kmeans_obj$cluster)
kmeans_obj$cluster <- mapping[as.character(kmeans_obj$cluster)]
names(kmeans_obj$cluster) <- old_names
kmeans_obj$size <- sort(kmeans_obj$size, decreasing = TRUE)
table(kmeans_obj$cluster)

data.frame(cluster=kmeans_obj$cluster) %>%
  # split(.$cluster)
  mutate(cluster=paste0("Cluster ", cluster, " n=", kmeans_obj$size[cluster])) %>%
  rownames_to_column("compound_name") %>%
  left_join(frac_labeled_df) %>%
  # ggplot() +
  # geom_boxplot(aes(x=timepoint_num, y=frac_labeled, color=startime, group=interaction(timepoint_num, startime))) +
  # facet_grid(depth~cluster)
  group_by(cluster, shortname) %>%
  summarise(mean_labeled=mean(frac_labeled, na.rm=TRUE)) %>%
  left_join(parametadata) %>%
  ggplot() +
  geom_point(aes(x=timepoint_num, y=mean_labeled, color=startime)) +
  facet_grid(depth~cluster)

library(randomForest)
library(rpart)
# library(rpart.plot)

(rfmodel <- randomForest(frac_mat, y=factor(kmeans_obj$cluster), ntree = 5000, 
                        importance=TRUE, proximity = TRUE, keep.forest = TRUE))
# varImpPlot(rfmodel, n.var = 60)
```


# Univariate followup

```{r}
amend_plot <- function(cmpd_name_i){
  amend_comp_concs %>%
    filter(compound_name==cmpd_name_i) %>%
    ggplot() +
    geom_col(aes(x=timepoint, y=nM_in_env, fill=labeled_n_count), color="black") +
    facet_grid2(depth~amendment, scales="free_y", space = "free", 
                strip = strip_themed(
                  background_x=elem_list_rect(fill = scales::hue_pal()(4)[c(1,4,3,2)])
                )) +
    scale_fill_gradient(low = "grey20", high = "grey80") +
    scale_y_continuous(expand = expansion(mult = c(0, 0.1))) +
    scale_x_discrete(breaks=c("T0", "T1", "T3", "T10", "T26", "T73"), labels=c("T0", 1,3,10,26, 73)) +
    theme_bw() +
    theme(text = element_text(size=14), legend.text = element_text(size=18), 
          legend.position = "none", strip.text = element_text(size=18)) +
    labs(x="Timepoint (hours after spike)", 
         y="Concentration (nM)\nin each 15N label",
         title = cmpd_name_i)
}
```

```{r}
parametadata <- read_csv("metadata/parametadata.csv") %>% 
  mutate(timepoint=fct_inorder(timepoint)) %>%
  mutate(depth=fct_inorder(depth)) %>%
  mutate(startime=fct_inorder(startime))
amm_iso_areas <- read_csv("untargeted/Amm_pos_noIS_output/iso_areas.csv") %>%
  select(-samp_type)

amm_iso_areas %>%
  filter(compound_name=="L-Glutamine") %>% # Or l-glutamine, or carnitine,
  left_join(parametadata) %>%
  filter(samp_type=="Smp") %>%
  ggplot() +
  # geom_col(aes(x=tripl, y=area, fill=labeled_n_count), position = "fill") +
  geom_col(aes(x=tripl, y=area, fill=labeled_n_count)) +
  facet_grid(depth~startime+timepoint, scales = "free_y") +
  theme(axis.text.x = element_blank(), axis.title.x = element_blank(), 
        axis.ticks.x=element_blank())

```

Demo written up for PARAGON group meeting:

```{r}
library(tidyverse)
amm_iso_areas <- read_csv("untargeted/Amm_pos_noIS_output/iso_areas.csv") %>%
  mutate(amend="Amm")
nit_iso_areas <- read_csv("untargeted/Nit_pos_noIS_output/iso_areas.csv") %>%
  mutate(amend="Nit")
parametadata <- read_csv("metadata/parametadata.csv")

library(ggh4x)
bind_rows(amm_iso_areas, nit_iso_areas) %>%
  filter(compound_name%in%c("L-Glutamine", "Guanine", "Shinorine?")) %>%
  mutate(compound_name=factor(compound_name, levels=c("L-Glutamine", "Guanine", "Shinorine?"))) %>%
  filter(samp_type=="Smp") %>%
  mutate(label_boolean=ifelse(labeled_n_count>0, "Labeled", "Unlabeled")) %>%
  left_join(parametadata) %>%
  # Shinorine isn't found in deep samples
  filter(!(compound_name=="Shinorine?" & depth=="Deep")) %>%
  # Add factors to order things correctly
  arrange(timepoint_num) %>%
  mutate(timepoint=fct_inorder(timepoint)) %>%
  mutate(startime=factor(startime, levels=c("Morn", "Eve"))) %>%
  mutate(depth=factor(depth, levels=c("Surf", "Deep"), labels=c("25m", "175m"))) %>%
  # Calculate label fractions
  group_by(amend, compound_name, timepoint, timepoint_num, label_boolean, labeled_n_count, tripl, depth, startime) %>%
  summarize(area=median(area)) %>%
  group_by(amend, compound_name, timepoint, timepoint_num, tripl, depth, startime) %>%
  mutate(area=area/sum(area)) %>%
  group_by(amend, compound_name, timepoint, timepoint_num, label_boolean, tripl, depth, startime) %>%
  summarise(area=sum(area)) %>%
  drop_na() %>%
  ggplot() +
  geom_col(aes(x=tripl, y=area, fill=label_boolean), position = "fill", width = 1, color="black") +
  facet_nested(compound_name+depth~amend+startime+timepoint) +
  scale_y_continuous(labels = scales::label_percent(), expand = expansion()) +
  scale_x_discrete(expand = expansion()) +
  scale_fill_manual(breaks=c("Unlabeled", "Labeled"), values = c("#a6cde3", "#1d7cb4")) +
  theme_bw() +
  theme(axis.text.x = element_blank(), axis.title.x = element_blank(), 
        axis.ticks.x = element_blank(), legend.position = "top") +
  labs(y="Fraction labeled", fill=NULL)



bind_rows(amm_iso_areas, nit_iso_areas) %>%
  filter(compound_name%in%c("L-Glutamine", "Guanine")) %>%
  mutate(compound_name=factor(compound_name, levels=c("L-Glutamine", "Guanine"))) %>%
  filter(samp_type=="Smp") %>%
  mutate(label_boolean=ifelse(labeled_n_count>0, "Labeled", "Unlabeled")) %>%
  left_join(parametadata) %>%
  filter(startime=="Morn") %>%
  filter(depth=="Surf") %>%
  arrange(timepoint_num) %>%
  mutate(timepoint=fct_inorder(timepoint)) %>%
  group_by(amend, compound_name, timepoint, timepoint_num, label_boolean, labeled_n_count, tripl) %>%
  summarize(area=median(area)) %>%
  group_by(amend, compound_name, timepoint, timepoint_num, tripl) %>%
  mutate(area=area/sum(area)) %>%
  group_by(amend, compound_name, timepoint, timepoint_num, label_boolean, tripl) %>%
  summarise(area=sum(area)) %>%
  ggplot() +
  geom_col(aes(x=tripl, y=area, fill=label_boolean), position = "fill", width = 1, color="black") +
  facet_nested(compound_name~amend+timepoint) +
  scale_y_continuous(labels = scales::label_percent(), expand = expansion()) +
  scale_x_discrete(expand = expansion()) +
  scale_fill_manual(breaks=c("Unlabeled", "Labeled"), values = c("#a6cde3", "#1d7cb4")) +
  theme_bw() +
  theme(axis.text.x = element_blank(), axis.title.x = element_blank(), 
        axis.ticks.x = element_blank(), legend.position = "top") +
  labs(y="Fraction labeled", fill=NULL)



bind_rows(amm_iso_areas, nit_iso_areas) %>%
  filter(compound_name%in%c("L-Glutamine", "Guanine")) %>%
  mutate(compound_name=factor(compound_name, levels=c("L-Glutamine", "Guanine"))) %>%
  filter(samp_type=="Smp") %>%
  mutate(label_boolean=ifelse(labeled_n_count>0, "Labeled", "Unlabeled")) %>%
  left_join(parametadata) %>%
  filter(startime=="Morn") %>%
  filter(depth=="Surf") %>%
  arrange(timepoint_num) %>%
  mutate(timepoint=fct_inorder(timepoint)) %>%
  group_by(amend, compound_name, timepoint, timepoint_num, label_boolean, labeled_n_count) %>%
  summarize(area=median(area)) %>%
  group_by(amend, compound_name, timepoint, timepoint_num) %>%
  mutate(area=area/sum(area)) %>%
  group_by(amend, compound_name, timepoint, timepoint_num, label_boolean) %>%
  summarise(area=sum(area)) %>%
  ggplot() +
  geom_col(aes(x=timepoint, y=area, fill=label_boolean), position = "fill", width = 1, color="black") +
  facet_nested(compound_name~amend) +
  scale_y_continuous(labels = scales::label_percent(), expand = expansion()) +
  scale_x_discrete(expand = expansion()) +
  scale_fill_manual(breaks=c("Labeled", "Unlabeled"), values = c("#1d7cb4", "#a6cde3")) +
  theme_bw() +
  theme(legend.position = "top") +
  labs(y="Fraction labeled", fill=NULL, x="Timepoint")
```

